# Motosiklet - Manuel Model Verileri
# Bu dosyayı çalıştırmak için: python manual_fill.py

import json, os

DATA = {
    "Aprilia": [
        {"model": "RSV4 Factory", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2021},
        {"model": "RSV4 1100 Factory", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2019},
        {"model": "RS 660", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2021},
        {"model": "Tuono V4 Factory", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2021},
        {"model": "Tuono 660", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2021},
        {"model": "RS 457", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2023},
        {"model": "Tuono 457", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2024},
        {"model": "RS 125", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2018},
        {"model": "SX 125", "kasa_tipleri": ["Supermoto"], "uretim_baslangic": 2019},
        {"model": "RX 125", "kasa_tipleri": ["Enduro"], "uretim_baslangic": 2019},
    ],
    "BMW Motorrad": [
        {"model": "S1000RR", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2019},
        {"model": "M1000R", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2023},
        {"model": "M1000RR", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2021},
        {"model": "R1300GS", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2023},
        {"model": "R1250GS", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2019, "uretim_bitis": 2023},
        {"model": "R1250GS Adventure", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2019},
        {"model": "R1250RT", "kasa_tipleri": ["Turizm"], "uretim_baslangic": 2019},
        {"model": "R1200GS", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2013, "uretim_bitis": 2018},
        {"model": "F900R", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2020},
        {"model": "F900XR", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2020},
        {"model": "F850GS", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2018},
        {"model": "F850GS Adventure", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2019},
        {"model": "F750GS", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2018},
        {"model": "G310R", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2016},
        {"model": "G310GS", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2017},
        {"model": "K1600GTL", "kasa_tipleri": ["Turizm"], "uretim_baslangic": 2011},
        {"model": "K1600B", "kasa_tipleri": ["Turizm"], "uretim_baslangic": 2017},
        {"model": "CE 04", "kasa_tipleri": ["Elektrikli Scooter"], "uretim_baslangic": 2022},
    ],
    "Benelli": [
        {"model": "Leoncino 500", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2016},
        {"model": "Leoncino 800", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2021},
        {"model": "TRK 502", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2016},
        {"model": "TRK 702", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2022},
        {"model": "302R", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2018},
        {"model": "502C", "kasa_tipleri": ["Cruiser"], "uretim_baslangic": 2017},
        {"model": "Imperiale 400", "kasa_tipleri": ["Klasik"], "uretim_baslangic": 2017},
    ],
    "CFMoto": [
        {"model": "700CL-X Heritage", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2020},
        {"model": "700CL-X Sport", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2020},
        {"model": "800MT", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2021},
        {"model": "650MT", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2017},
        {"model": "650NK", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2016},
        {"model": "450NK", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2023},
        {"model": "450SR", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2022},
        {"model": "300NK", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2018},
        {"model": "300SR", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2021},
        {"model": "250CL-X", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2021},
        {"model": "Papio", "kasa_tipleri": ["Mini"], "uretim_baslangic": 2019},
    ],
    "Ducati": [
        {"model": "Panigale V4 R", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2019},
        {"model": "Panigale V4 S", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2018},
        {"model": "Panigale V2", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2020},
        {"model": "Streetfighter V4 S", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2020},
        {"model": "Streetfighter V2", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2022},
        {"model": "Monster SP", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2021},
        {"model": "Monster 937", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2021},
        {"model": "Multistrada V4 S", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2021},
        {"model": "Multistrada V4 Rally", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2022},
        {"model": "Multistrada V2", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2022},
        {"model": "Diavel V4", "kasa_tipleri": ["Power Cruiser"], "uretim_baslangic": 2023},
        {"model": "Supersport 950", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2017},
        {"model": "Scrambler Full Throttle", "kasa_tipleri": ["Scrambler"], "uretim_baslangic": 2022},
        {"model": "Scrambler Icon", "kasa_tipleri": ["Scrambler"], "uretim_baslangic": 2015},
        {"model": "Hypermotard 950", "kasa_tipleri": ["Motard"], "uretim_baslangic": 2019},
    ],
    "Harley-Davidson": [
        {"model": "Street Glide", "kasa_tipleri": ["Touring"], "uretim_baslangic": 2014},
        {"model": "Road Glide", "kasa_tipleri": ["Touring"], "uretim_baslangic": 2015},
        {"model": "Road King", "kasa_tipleri": ["Touring"], "uretim_baslangic": 2014},
        {"model": "Electra Glide", "kasa_tipleri": ["Touring"], "uretim_baslangic": 2014, "uretim_bitis": 2022},
        {"model": "Ultra Limited", "kasa_tipleri": ["Touring"], "uretim_baslangic": 2014},
        {"model": "Fat Boy 114", "kasa_tipleri": ["Cruiser"], "uretim_baslangic": 2018},
        {"model": "Heritage Classic 114", "kasa_tipleri": ["Cruiser"], "uretim_baslangic": 2018},
        {"model": "Low Rider S", "kasa_tipleri": ["Cruiser"], "uretim_baslangic": 2020},
        {"model": "Street Bob 114", "kasa_tipleri": ["Cruiser"], "uretim_baslangic": 2018},
        {"model": "Iron 883", "kasa_tipleri": ["Cruiser"], "uretim_baslangic": 2009, "uretim_bitis": 2022},
        {"model": "Forty-Eight", "kasa_tipleri": ["Cruiser"], "uretim_baslangic": 2010},
        {"model": "Sportster S", "kasa_tipleri": ["Cruiser"], "uretim_baslangic": 2021},
        {"model": "Nightster", "kasa_tipleri": ["Cruiser"], "uretim_baslangic": 2022},
        {"model": "Pan America 1250", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2021},
        {"model": "LiveWire S2 Del Mar", "kasa_tipleri": ["Elektrikli"], "uretim_baslangic": 2023},
    ],
    "Honda Motorcycle": [
        {"model": "CBR1000RR-R Fireblade", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2020},
        {"model": "CBR650R", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2019},
        {"model": "CB650R", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2019},
        {"model": "CB500F", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2013},
        {"model": "CB125F", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2015},
        {"model": "Africa Twin CRF1100L", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2020},
        {"model": "CRF300L", "kasa_tipleri": ["Enduro"], "uretim_baslangic": 2021},
        {"model": "CRF450R", "kasa_tipleri": ["Motokros"], "uretim_baslangic": 2019},
        {"model": "Gold Wing GL1800", "kasa_tipleri": ["Touring"], "uretim_baslangic": 2018},
        {"model": "NC750X", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2014},
        {"model": "X-ADV 750", "kasa_tipleri": ["Scooter", "Adventure"], "uretim_baslangic": 2017},
        {"model": "Forza 750", "kasa_tipleri": ["Scooter"], "uretim_baslangic": 2021},
        {"model": "Forza 350", "kasa_tipleri": ["Scooter"], "uretim_baslangic": 2021},
        {"model": "Forza 125", "kasa_tipleri": ["Scooter"], "uretim_baslangic": 2015},
        {"model": "PCX 125", "kasa_tipleri": ["Scooter"], "uretim_baslangic": 2010},
        {"model": "SH 125", "kasa_tipleri": ["Scooter"], "uretim_baslangic": 2015},
        {"model": "CB1000R", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2018},
        {"model": "CBR600RR", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2003, "uretim_bitis": 2024},
        {"model": "VFR800F", "kasa_tipleri": ["Sport Turizm"], "uretim_baslangic": 2014, "uretim_bitis": 2020},
        {"model": "NT1100", "kasa_tipleri": ["Turizm"], "uretim_baslangic": 2022},
        {"model": "CB300R", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2018},
        {"model": "MONKEY 125", "kasa_tipleri": ["Mini"], "uretim_baslangic": 2018},
        {"model": "GROM MSX125", "kasa_tipleri": ["Mini"], "uretim_baslangic": 2013},
        {"model": "CBR500R", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2013},
        {"model": "CB500X", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2013},
        {"model": "XL750 Transalp", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2023},
    ],
    "Husqvarna Motorcycles": [
        {"model": "Vitpilen 401", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2018},
        {"model": "Vitpilen 250", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2019},
        {"model": "Svartpilen 401", "kasa_tipleri": ["Scrambler"], "uretim_baslangic": 2018},
        {"model": "Svartpilen 250", "kasa_tipleri": ["Scrambler"], "uretim_baslangic": 2019},
        {"model": "Norden 901", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2022},
        {"model": "TE 300i", "kasa_tipleri": ["Enduro"], "uretim_baslangic": 2017},
        {"model": "FE 350", "kasa_tipleri": ["Enduro"], "uretim_baslangic": 2017},
        {"model": "FC 450", "kasa_tipleri": ["Motokros"], "uretim_baslangic": 2017},
    ],
    "Indian Motorcycle": [
        {"model": "Scout Bobber", "kasa_tipleri": ["Cruiser"], "uretim_baslangic": 2018},
        {"model": "Scout Sixty", "kasa_tipleri": ["Cruiser"], "uretim_baslangic": 2016},
        {"model": "Chief Dark Horse", "kasa_tipleri": ["Cruiser"], "uretim_baslangic": 2021},
        {"model": "Chief Bobber", "kasa_tipleri": ["Cruiser"], "uretim_baslangic": 2021},
        {"model": "Springfield", "kasa_tipleri": ["Touring"], "uretim_baslangic": 2016},
        {"model": "Challenger", "kasa_tipleri": ["Touring"], "uretim_baslangic": 2020},
        {"model": "Roadmaster Elite", "kasa_tipleri": ["Touring"], "uretim_baslangic": 2022},
        {"model": "FTR 1200", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2019},
        {"model": "FTR R Carbon", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2021},
    ],
    "KTM": [
        {"model": "1290 Super Duke R", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2014},
        {"model": "1290 Super Adventure S", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2015},
        {"model": "1290 Super Adventure R", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2015},
        {"model": "890 Duke R", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2020},
        {"model": "890 Adventure R", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2020},
        {"model": "790 Duke", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2018},
        {"model": "390 Duke", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2013},
        {"model": "390 Adventure", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2020},
        {"model": "250 Duke", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2017},
        {"model": "125 Duke", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2013},
        {"model": "RC 390", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2014},
        {"model": "RC 125", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2014},
        {"model": "450 SMR", "kasa_tipleri": ["Supermoto"], "uretim_baslangic": 2024},
        {"model": "250 EXC-F", "kasa_tipleri": ["Enduro"], "uretim_baslangic": 2017},
        {"model": "350 EXC-F", "kasa_tipleri": ["Enduro"], "uretim_baslangic": 2012},
        {"model": "450 EXC-F", "kasa_tipleri": ["Enduro"], "uretim_baslangic": 2012},
    ],
    "Kawasaki": [
        {"model": "Ninja H2", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2015},
        {"model": "Ninja H2R", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2015},
        {"model": "Ninja ZX-10R", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2016},
        {"model": "Ninja ZX-6R", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2013},
        {"model": "Ninja 650", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2012},
        {"model": "Ninja 400", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2018},
        {"model": "Ninja 125", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2019},
        {"model": "Z H2", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2020},
        {"model": "Z900", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2017},
        {"model": "Z650", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2017},
        {"model": "Z400", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2019},
        {"model": "Z125 Pro", "kasa_tipleri": ["Mini"], "uretim_baslangic": 2015},
        {"model": "Versys 1000", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2015},
        {"model": "Versys 650", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2015},
        {"model": "Versys-X 300", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2017},
        {"model": "KX450", "kasa_tipleri": ["Motokros"], "uretim_baslangic": 2019},
        {"model": "KX250", "kasa_tipleri": ["Motokros"], "uretim_baslangic": 2019},
        {"model": "KX85", "kasa_tipleri": ["Motokros"], "uretim_baslangic": 2014},
        {"model": "KLX300R", "kasa_tipleri": ["Enduro"], "uretim_baslangic": 2021},
        {"model": "KLX140R", "kasa_tipleri": ["Enduro"], "uretim_baslangic": 2014},
        {"model": "W800", "kasa_tipleri": ["Klasik"], "uretim_baslangic": 2019},
        {"model": "Z900RS", "kasa_tipleri": ["Klasik Naked"], "uretim_baslangic": 2017},
        {"model": "Eliminator 500", "kasa_tipleri": ["Cruiser"], "uretim_baslangic": 2023},
        {"model": "Vulcan S", "kasa_tipleri": ["Cruiser"], "uretim_baslangic": 2015},
    ],
    "MV Agusta": [
        {"model": "F4 RC", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2016, "uretim_bitis": 2018},
        {"model": "Brutale 1000 RR", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2020},
        {"model": "Dragster 800 RR", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2016},
        {"model": "F3 800 RC", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2017},
        {"model": "Superveloce 800", "kasa_tipleri": ["Naked Klasik"], "uretim_baslangic": 2019},
        {"model": "Turismo Veloce 800", "kasa_tipleri": ["Sport Turizm"], "uretim_baslangic": 2015},
        {"model": "Lucky Explorer 5.5", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2023},
    ],
    "Piaggio": [
        {"model": "Vespa Primavera 125", "kasa_tipleri": ["Scooter"], "uretim_baslangic": 2013},
        {"model": "Vespa Primavera 150", "kasa_tipleri": ["Scooter"], "uretim_baslangic": 2013},
        {"model": "Vespa Sprint 150", "kasa_tipleri": ["Scooter"], "uretim_baslangic": 2014},
        {"model": "Vespa GTS 300", "kasa_tipleri": ["Scooter"], "uretim_baslangic": 2014},
        {"model": "Vespa GTV 300", "kasa_tipleri": ["Scooter"], "uretim_baslangic": 2016},
        {"model": "Vespa Elettrica", "kasa_tipleri": ["Elektrikli Scooter"], "uretim_baslangic": 2018},
        {"model": "Piaggio Liberty 125", "kasa_tipleri": ["Scooter"], "uretim_baslangic": 2012},
        {"model": "Piaggio Liberty 150", "kasa_tipleri": ["Scooter"], "uretim_baslangic": 2012},
        {"model": "Piaggio Beverly 300", "kasa_tipleri": ["Scooter"], "uretim_baslangic": 2016},
        {"model": "Piaggio BV 400", "kasa_tipleri": ["Scooter"], "uretim_baslangic": 2022},
        {"model": "Piaggio MP3 300", "kasa_tipleri": ["Trike Scooter"], "uretim_baslangic": 2013},
        {"model": "Piaggio MP3 500", "kasa_tipleri": ["Trike Scooter"], "uretim_baslangic": 2013},
    ],
    "Royal Enfield": [
        {"model": "Hunter 350", "kasa_tipleri": ["Klasik"], "uretim_baslangic": 2022},
        {"model": "Classic 350", "kasa_tipleri": ["Klasik"], "uretim_baslangic": 2021},
        {"model": "Bullet 350", "kasa_tipleri": ["Klasik"], "uretim_baslangic": 2021},
        {"model": "Meteor 350", "kasa_tipleri": ["Cruiser"], "uretim_baslangic": 2021},
        {"model": "Super Meteor 650", "kasa_tipleri": ["Cruiser"], "uretim_baslangic": 2022},
        {"model": "Interceptor 650", "kasa_tipleri": ["Klasik Naked"], "uretim_baslangic": 2018},
        {"model": "Continental GT 650", "kasa_tipleri": ["Klasik Sport"], "uretim_baslangic": 2018},
        {"model": "Himalayan 450", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2023},
        {"model": "Scram 411", "kasa_tipleri": ["Scrambler"], "uretim_baslangic": 2022},
        {"model": "Shotgun 650", "kasa_tipleri": ["Cruiser"], "uretim_baslangic": 2023},
    ],
    "Suzuki Motorcycle": [
        {"model": "GSX-R1000R", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2017},
        {"model": "GSX-R750", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2011},
        {"model": "GSX-R600", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2011, "uretim_bitis": 2020},
        {"model": "GSX-S1000", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2015},
        {"model": "GSX-S750", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2015},
        {"model": "GSX-8S", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2023},
        {"model": "GSX-8R", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2024},
        {"model": "Hayabusa", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2021},
        {"model": "V-Strom 1050", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2020},
        {"model": "V-Strom 800DE", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2023},
        {"model": "V-Strom 650XT", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2017},
        {"model": "Address 125", "kasa_tipleri": ["Scooter"], "uretim_baslangic": 2013},
        {"model": "Burgman Street 125", "kasa_tipleri": ["Scooter"], "uretim_baslangic": 2017},
        {"model": "SV650", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2016},
        {"model": "Katana", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2019},
    ],
    "Triumph": [
        {"model": "Street Triple RS 765", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2023},
        {"model": "Street Triple 765 R", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2017},
        {"model": "Speed Triple 1200 RS", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2021},
        {"model": "Speed Triple 1200 RR", "kasa_tipleri": ["Naked Klasik"], "uretim_baslangic": 2022},
        {"model": "Trident 660", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2021},
        {"model": "Tiger 1200 Rally Explorer", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2022},
        {"model": "Tiger 900 Rally Pro", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2020},
        {"model": "Tiger 900 GT", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2020},
        {"model": "Tiger Sport 660", "kasa_tipleri": ["Sport Turizm"], "uretim_baslangic": 2022},
        {"model": "Bonneville T120", "kasa_tipleri": ["Klasik"], "uretim_baslangic": 2016},
        {"model": "Bonneville T100", "kasa_tipleri": ["Klasik"], "uretim_baslangic": 2016},
        {"model": "Bonneville Speedmaster", "kasa_tipleri": ["Klasik Cruiser"], "uretim_baslangic": 2018},
        {"model": "Street Twin / Speed 400", "kasa_tipleri": ["Klasik"], "uretim_baslangic": 2024},
        {"model": "Scrambler 900", "kasa_tipleri": ["Scrambler"], "uretim_baslangic": 2016},
        {"model": "Scrambler 1200 XE", "kasa_tipleri": ["Scrambler"], "uretim_baslangic": 2019},
        {"model": "Rocket 3 Storm R", "kasa_tipleri": ["Power Cruiser"], "uretim_baslangic": 2024},
        {"model": "Thruxton 1200 RS", "kasa_tipleri": ["Klasik Sport"], "uretim_baslangic": 2020},
    ],
    "Yamaha": [
        {"model": "YZF-R1", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2015},
        {"model": "YZF-R6", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2017, "uretim_bitis": 2020},
        {"model": "YZF-R7", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2022},
        {"model": "YZF-R3", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2015},
        {"model": "YZF-R125", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2015},
        {"model": "MT-10", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2016},
        {"model": "MT-09", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2014},
        {"model": "MT-07", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2014},
        {"model": "MT-03", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2016},
        {"model": "MT-125", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2014},
        {"model": "Tracer 9", "kasa_tipleri": ["Sport Turizm"], "uretim_baslangic": 2018},
        {"model": "Tracer 7", "kasa_tipleri": ["Sport Turizm"], "uretim_baslangic": 2021},
        {"model": "XSR900", "kasa_tipleri": ["Naked Klasik"], "uretim_baslangic": 2016},
        {"model": "XSR700", "kasa_tipleri": ["Naked Klasik"], "uretim_baslangic": 2016},
        {"model": "Super Ténéré XT1200Z", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2010},
        {"model": "Ténéré 700", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2019},
        {"model": "Tenere 700 World Raid", "kasa_tipleri": ["Adventure"], "uretim_baslangic": 2022},
        {"model": "Niken GT", "kasa_tipleri": ["Sport Turizm"], "uretim_baslangic": 2018},
        {"model": "XMAX 300", "kasa_tipleri": ["Scooter"], "uretim_baslangic": 2017},
        {"model": "XMAX 125", "kasa_tipleri": ["Scooter"], "uretim_baslangic": 2017},
        {"model": "TMAX 560", "kasa_tipleri": ["Scooter"], "uretim_baslangic": 2020},
        {"model": "NMAX 125", "kasa_tipleri": ["Scooter"], "uretim_baslangic": 2015},
        {"model": "MT-15", "kasa_tipleri": ["Naked"], "uretim_baslangic": 2019},
        {"model": "YZF-R15", "kasa_tipleri": ["Sport"], "uretim_baslangic": 2018},
        {"model": "Bolt R-Spec", "kasa_tipleri": ["Cruiser"], "uretim_baslangic": 2014},
        {"model": "VMAX", "kasa_tipleri": ["Power Cruiser"], "uretim_baslangic": 2009, "uretim_bitis": 2020},
    ],
}

os.makedirs("modeller", exist_ok=True)
combined = []
for brand, models in sorted(DATA.items()):
    dosya_adi = brand.lower().replace(" ","_").replace("ü","u").replace("ö","o").replace("ı","i").replace("ş","s").replace("ç","c").replace("ğ","g")
    entry = {"marka": brand, "modeller": models, "kaynak": "manuel"}
    with open(f"modeller/{dosya_adi}.json", "w", encoding="utf-8") as f:
        json.dump(entry, f, ensure_ascii=False, indent=2)
    combined.append(entry)
    print(f"{brand}: {len(models)} model")
combined.sort(key=lambda x: x["marka"])
with open("tum_modeller.json", "w", encoding="utf-8") as f:
    json.dump(combined, f, ensure_ascii=False, indent=2)
print(f"Toplam: {len(combined)} marka, {sum(len(m[\"modeller\"]) for m in combined)} model")
