from sqlalchemy import Column, Integer, String, Float, Boolean, Text, ForeignKey, func
from src.database import Base


class CargoCompany(Base):
    __tablename__ = "cargo_companies"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    company_name = Column(String(255), nullable=False)
    slug = Column(String(255), unique=True, nullable=False, index=True)
    tax_id = Column(String(50))
    tax_office = Column(String(100))
    phone = Column(String(20))
    email = Column(String(255))
    website = Column(String(500))
    description = Column(Text)
    logo_url = Column(String(500))
    cover_url = Column(String(500))
    city = Column(String(100))
    district = Column(String(100))
    address = Column(Text)
    latitude = Column(Float)
    longitude = Column(Float)
    api_key = Column(String(64))
    api_webhook_url = Column(String(500))
    api_allowed_ips = Column(String)
    is_verified = Column(Boolean, default=False)
    verification_status = Column(String(20), default="pending")
    verification_doc_url = Column(String(500))
    is_active = Column(Boolean, default=True)
    rating = Column(Float, default=0)
    review_count = Column(Integer, default=0)
    shipment_count = Column(Integer, default=0)
    created_at = Column(String, server_default=func.datetime("now"))
    updated_at = Column(String, server_default=func.datetime("now"))


class CargoBranch(Base):
    __tablename__ = "cargo_branches"
    id = Column(Integer, primary_key=True, index=True)
    company_id = Column(Integer, ForeignKey("cargo_companies.id"), nullable=False)
    branch_name = Column(String(255), nullable=False)
    branch_code = Column(String(50))
    phone = Column(String(20))
    email = Column(String(255))
    city = Column(String(100), nullable=False)
    district = Column(String(100))
    address = Column(Text, nullable=False)
    latitude = Column(Float)
    longitude = Column(Float)
    is_main_branch = Column(Boolean, default=False)
    is_active = Column(Boolean, default=True)
    working_hours = Column(String)
    manager_name = Column(String(255))
    capacity_daily = Column(Integer)
    created_at = Column(String, server_default=func.datetime("now"))


class CargoCourier(Base):
    __tablename__ = "cargo_couriers"
    id = Column(Integer, primary_key=True, index=True)
    company_id = Column(Integer, ForeignKey("cargo_companies.id"), nullable=False)
    branch_id = Column(Integer, ForeignKey("cargo_branches.id"))
    user_id = Column(Integer, ForeignKey("users.id"))
    full_name = Column(String(255), nullable=False)
    phone = Column(String(20), nullable=False)
    email = Column(String(255))
    tc_kimlik = Column(String(11))
    vehicle_type = Column(String(50))
    vehicle_plate = Column(String(20))
    license_no = Column(String(50))
    is_active = Column(Boolean, default=True)
    is_available = Column(Boolean, default=True)
    current_latitude = Column(Float)
    current_longitude = Column(Float)
    last_location_update = Column(String)
    rating = Column(Float, default=0)
    total_deliveries = Column(Integer, default=0)
    created_at = Column(String, server_default=func.datetime("now"))


class CargoShipment(Base):
    __tablename__ = "cargo_shipments"
    id = Column(Integer, primary_key=True, index=True)
    company_id = Column(Integer, ForeignKey("cargo_companies.id"), nullable=False)
    branch_id = Column(Integer, ForeignKey("cargo_branches.id"))
    courier_id = Column(Integer, ForeignKey("cargo_couriers.id"))
    sender_name = Column(String(255), nullable=False)
    sender_phone = Column(String(20))
    sender_email = Column(String(255))
    sender_city = Column(String(100))
    sender_district = Column(String(100))
    sender_address = Column(Text)
    sender_latitude = Column(Float)
    sender_longitude = Column(Float)
    recipient_name = Column(String(255), nullable=False)
    recipient_phone = Column(String(20))
    recipient_email = Column(String(255))
    recipient_city = Column(String(100), nullable=False)
    recipient_district = Column(String(100))
    recipient_address = Column(Text, nullable=False)
    recipient_latitude = Column(Float)
    recipient_longitude = Column(Float)
    tracking_no = Column(String(50), unique=True, nullable=False, index=True)
    reference_no = Column(String(100))
    barcode = Column(String(100))
    weight_kg = Column(Float)
    volume_dm3 = Column(Float)
    piece_count = Column(Integer, default=1)
    package_type = Column(String(50))
    description = Column(Text)
    status = Column(String(30), default="hazirlaniyor")
    is_express = Column(Boolean, default=False)
    is_international = Column(Boolean, default=False)
    total_price = Column(Float)
    currency = Column(String(10), default="TRY")
    is_paid = Column(Boolean, default=False)
    payment_method = Column(String(30))
    source_module = Column(String(50))
    source_order_id = Column(Integer)
    delivery_code = Column(String(10))
    delivery_confirmed_by_recipient = Column(Boolean, default=False)
    delivery_confirmed_at = Column(String)
    delivery_note = Column(Text)
    delivery_photo_url = Column(String(500))
    is_fragile = Column(Boolean, default=False)
    sensitivity_note = Column(String(255))
    requires_signature = Column(Boolean, default=False)
    pickup_confirmed_by_courier = Column(Boolean, default=False)
    pickup_confirmed_at = Column(String)
    pickup_photo_url = Column(String(500))
    pickup_note = Column(Text)
    delivery_attempt_count = Column(Integer, default=0)
    last_delivery_attempt_at = Column(String)
    undelivered_reason = Column(String(255))
    branch_wait_until = Column(String)
    customer_extended_pickup = Column(Boolean, default=False)
    customer_pickup_deadline = Column(String)
    refund_amount = Column(Float)
    refund_delivery_cost = Column(Float)
    refund_return_cost = Column(Float)
    refund_net_amount = Column(Float)
    refund_processed = Column(Boolean, default=False)
    refund_processed_at = Column(String)
    estimated_delivery_date = Column(String)
    actual_delivery_date = Column(String)
    created_at = Column(String, server_default=func.datetime("now"))
    updated_at = Column(String, server_default=func.datetime("now"))


class CargoTracking(Base):
    __tablename__ = "cargo_tracking"
    id = Column(Integer, primary_key=True, index=True)
    shipment_id = Column(Integer, ForeignKey("cargo_shipments.id"), nullable=False)
    status = Column(String(30), nullable=False)
    location_name = Column(String(255))
    latitude = Column(Float)
    longitude = Column(Float)
    notes = Column(Text)
    created_by = Column(String(50))
    created_at = Column(String, server_default=func.datetime("now"))


class CargoPricingTier(Base):
    __tablename__ = "cargo_pricing_tiers"
    id = Column(Integer, primary_key=True, index=True)
    company_id = Column(Integer, ForeignKey("cargo_companies.id"), nullable=False)
    tier_name = Column(String(100), nullable=False)
    min_weight_kg = Column(Float, default=0)
    max_weight_kg = Column(Float)
    min_volume_dm3 = Column(Float, default=0)
    max_volume_dm3 = Column(Float)
    zone_type = Column(String(30))
    base_price = Column(Float, nullable=False)
    price_per_kg = Column(Float, default=0)
    price_per_dm3 = Column(Float, default=0)
    fuel_surcharge_percent = Column(Float, default=0)
    is_active = Column(Boolean, default=True)
    created_at = Column(String, server_default=func.datetime("now"))


class CargoServiceArea(Base):
    __tablename__ = "cargo_service_areas"
    id = Column(Integer, primary_key=True, index=True)
    company_id = Column(Integer, ForeignKey("cargo_companies.id"), nullable=False)
    branch_id = Column(Integer, ForeignKey("cargo_branches.id"))
    city = Column(String(100), nullable=False)
    district = Column(String(100))
    is_available = Column(Boolean, default=True)
    delivery_time_hours = Column(Integer)
    pickup_available = Column(Boolean, default=True)
    daily_capacity = Column(Integer)
    notes = Column(Text)
    created_at = Column(String, server_default=func.datetime("now"))


class CargoReturnRequest(Base):
    __tablename__ = "cargo_return_requests"
    id = Column(Integer, primary_key=True, index=True)
    shipment_id = Column(Integer, ForeignKey("cargo_shipments.id"), nullable=False)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    reason = Column(String(255), nullable=False)
    description = Column(Text)
    evidence_photos = Column(String)
    evidence_videos = Column(String)
    status = Column(String(30), default="beklemede")
    is_within_window = Column(Boolean)
    liability_party = Column(String(20))
    liable_amount = Column(Float)
    replacement_required = Column(Boolean, default=False)
    replacement_shipped = Column(Boolean, default=False)
    reviewed_by = Column(Integer, ForeignKey("users.id"))
    review_notes = Column(Text)
    resolution = Column(String(30))
    created_at = Column(String, server_default=func.datetime("now"))
    updated_at = Column(String, server_default=func.datetime("now"))


class CargoSellerSuspension(Base):
    __tablename__ = "cargo_seller_suspensions"
    id = Column(Integer, primary_key=True, index=True)
    seller_id = Column(Integer, ForeignKey("sellers.id"), nullable=False)
    offense_count = Column(Integer, nullable=False)
    suspension_days = Column(Integer, nullable=False)
    start_date = Column(String, server_default=func.datetime("now"))
    end_date = Column(String, nullable=False)
    reason = Column(Text)
    is_active = Column(Boolean, default=True)
    created_at = Column(String, server_default=func.datetime("now"))


class CargoSellerAgreement(Base):
    __tablename__ = "cargo_seller_agreements"
    id = Column(Integer, primary_key=True, index=True)
    seller_id = Column(Integer, ForeignKey("sellers.id"), nullable=False)
    company_id = Column(Integer, ForeignKey("cargo_companies.id"), nullable=False)
    is_preferred = Column(Boolean, default=False)
    contract_start = Column(String)
    contract_end = Column(String)
    negotiated_price_factor = Column(Float, default=1.0)
    notes = Column(Text)
    is_active = Column(Boolean, default=True)
    created_at = Column(String, server_default=func.datetime("now"))


class CargoProductShipping(Base):
    __tablename__ = "cargo_product_shipping"
    id = Column(Integer, primary_key=True, index=True)
    seller_id = Column(Integer, ForeignKey("sellers.id"), nullable=False)
    product_id = Column(Integer)
    company_id = Column(Integer, ForeignKey("cargo_companies.id"), nullable=False)
    estimated_delivery_hours = Column(Integer)
    max_delivery_days = Column(Integer)
    available_days = Column(String(100))
    max_distance_km = Column(Float)
    sensitivity_level = Column(String(20), default="normal")
    is_fragile = Column(Boolean, default=False)
    requires_special_packaging = Column(Boolean, default=False)
    packaging_instructions = Column(Text)
    shipping_price = Column(Float)
    free_shipping_min_amount = Column(Float)
    is_free_shipping = Column(Boolean, default=False)
    is_active = Column(Boolean, default=True)
    created_at = Column(String, server_default=func.datetime("now"))


class CargoDeliverySurvey(Base):
    __tablename__ = "cargo_delivery_surveys"
    id = Column(Integer, primary_key=True, index=True)
    shipment_id = Column(Integer, ForeignKey("cargo_shipments.id"), nullable=False)
    user_id = Column(Integer, ForeignKey("users.id"))
    delivered_on_time = Column(Boolean)
    package_condition = Column(String(30))
    is_package_damaged = Column(Boolean)
    is_package_opened = Column(Boolean)
    satisfaction_score = Column(Integer)
    courier_rating = Column(Integer)
    comment = Column(Text)
    photo_url = Column(String(500))
    created_at = Column(String, server_default=func.datetime("now"))
