package api

import (
	"encoding/json"
	"net/http"

	"github.com/go-chi/chi/v5"
	chimw "github.com/go-chi/chi/v5/middleware"
	"github.com/go-chi/cors"
	"github.com/go-chi/httprate"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/web-platform/backend/internal/api/handler"
	"github.com/web-platform/backend/internal/api/middleware"
	"github.com/web-platform/backend/internal/config"
	"github.com/web-platform/backend/internal/infra"
	"github.com/web-platform/backend/internal/repository/postgres"
)

func NewRouter(cfg *config.Config, pool *pgxpool.Pool, cache *infra.Cache, osrm *infra.OSRMClient) *chi.Mux {
	r := chi.NewRouter()

	r.Use(chimw.RequestID)
	r.Use(chimw.RealIP)
	r.Use(chimw.Logger)
	r.Use(chimw.Recoverer)
	r.Use(cors.Handler(middleware.CORS(cfg.CorsOrigin)))
	r.Use(httprate.LimitByIP(100, 60))

	userRepo := postgres.NewUserRepo(pool)
	productRepo := postgres.NewProductRepo(pool)
	orderRepo := postgres.NewOrderRepo(pool)
	courierRepo := postgres.NewCourierRepo(pool)
	rideRepo := postgres.NewRideRepo(pool)
	foodRepo := postgres.NewFoodRepo(pool)
	binaRepo := postgres.NewBinaRepo(pool)
	supportRepo := postgres.NewSupportRepo(pool)
	vehicleRepo := postgres.NewVehicleRepo(pool)
	expertRepo := postgres.NewExpertRepo(pool)
	realestateRepo := postgres.NewRealEstateRepo(pool)
	foodSupplierRepo := postgres.NewFoodSupplierRepo(pool)
	cicekRepo := postgres.NewCicekRepo(pool)
	vehicleListingRepo := postgres.NewVehicleListingRepo(pool)
	cargoRepo := postgres.NewCargoRepo(pool)

	authH := handler.NewAuthHandler(userRepo, cfg.JWTSecret)
	productH := handler.NewProductHandler(productRepo)
	orderH := handler.NewOrderHandler(orderRepo)
	courierH := handler.NewCourierHandler(courierRepo)
	rideH := handler.NewRideHandler(rideRepo, osrm)
	foodH := handler.NewFoodHandler(foodRepo)
	binaH := handler.NewBinaHandler(binaRepo)
	supportH := handler.NewSupportHandler(supportRepo)
	vehicleH := handler.NewVehicleHandler(vehicleRepo)
	expertH := handler.NewExpertHandler(expertRepo)
	realestateH := handler.NewRealEstateHandler(realestateRepo)
	foodSupplierH := handler.NewFoodSupplierHandler(foodSupplierRepo)
	cicekH := handler.NewCicekHandler(cicekRepo)
	vehicleListingH := handler.NewVehicleListingHandler(vehicleListingRepo)
	cargoH := handler.NewCargoHandler(cargoRepo)

	r.Route("/api/v1", func(r chi.Router) {
		r.Post("/auth/register", authH.Register)
		r.Post("/auth/login", authH.Login)

		r.Get("/products", productH.List)
		r.Get("/products/{id}", productH.Get)

		r.Group(func(r chi.Router) {
			r.Use(middleware.JWTAuth(cfg.JWTSecret))

			r.Post("/orders", orderH.Create)
			r.Get("/orders", orderH.ListMy)
			r.Get("/orders/{id}", orderH.Get)

			r.Group(func(r chi.Router) {
				r.Use(middleware.RequireRole("seller", "admin"))
				r.Post("/products", productH.Create)
				r.Put("/products/{id}", productH.Update)
				r.Delete("/products/{id}", productH.Delete)
			})

			r.Get("/couriers/nearby", courierH.GetNearby)

			r.Post("/rides/estimate", rideH.Estimate)
			r.Post("/rides", rideH.Create)
			r.Get("/rides/{id}", rideH.Get)

			// Food / Restaurants
			r.Group(func(r chi.Router) {
				r.Use(middleware.RequireRole("seller", "admin"))
				r.Post("/food/restaurants", foodH.RegisterRestaurant)
				r.Put("/food/restaurants/{rest_id}", foodH.UpdateRestaurant)
				r.Put("/food/restaurants/{rest_id}/verify", foodH.VerifyRestaurant)
				r.Post("/food/menu", foodH.CreateMenuItem)
				r.Put("/food/menu/{item_id}", foodH.UpdateMenuItem)
				r.Delete("/food/menu/{item_id}", foodH.DeleteMenuItem)
				r.Post("/food/menu/{item_id}/modifiers", foodH.AddModifier)
				r.Delete("/food/menu/{item_id}/modifiers/{mod_id}", foodH.DeleteModifier)
				r.Post("/food/restaurants/{rest_id}/branches", foodH.AddBranch)
				r.Post("/food/restaurants/{rest_id}/zones", foodH.AddZone)
			})

			r.Get("/food/restaurants", foodH.ListRestaurants)
			r.Get("/food/menu/{rest_id}", foodH.GetMenu)
			r.Get("/food/restaurants/{rest_id}/branches", foodH.ListBranches)
			r.Get("/food/restaurants/{rest_id}/zones", foodH.ListZones)

			// Food Suppliers / Traceability
			r.Post("/food/suppliers", foodSupplierH.CreateSupplier)
			r.Get("/food/suppliers", foodSupplierH.ListSuppliers)
			r.Get("/food/suppliers/{supplier_id}", foodSupplierH.GetSupplier)
			r.Get("/food/suppliers/page/{slug}", foodSupplierH.GetSupplierBySlug)
			r.Post("/food/suppliers/{supplier_id}/products", foodSupplierH.CreateProduct)
			r.Get("/food/suppliers/{supplier_id}/products", foodSupplierH.ListProducts)
			r.Post("/food/restaurants/{rest_id}/suppliers", foodSupplierH.LinkSupplier)
			r.Delete("/food/restaurants/{rest_id}/suppliers/{supplier_id}", foodSupplierH.UnlinkSupplier)
			r.Get("/food/restaurants/{rest_id}/suppliers", foodSupplierH.ListRestaurantSuppliers)
			r.Post("/food/menu/{item_id}/ingredients", foodSupplierH.CreateIngredient)
			r.Delete("/food/ingredients/{ingredient_id}", foodSupplierH.DeleteIngredient)
			r.Get("/food/menu/{item_id}/ingredients", foodSupplierH.ListIngredients)
			r.Get("/food/trace/{item_id}", foodSupplierH.TraceMenuItem)

			// Bina / Site Yonetimi
			r.Post("/bina/site", binaH.CreateSite)
			r.Get("/bina/site/{id}", binaH.GetSite)
			r.Put("/bina/site/{id}", binaH.UpdateSite)
			r.Post("/bina/kurulum", binaH.Kurulum)
			r.Get("/bina/blok", binaH.ListBlok)
			r.Get("/bina/daire", binaH.ListDaire)
			r.Post("/bina/kisi", binaH.CreateKisi)
			r.Get("/bina/kisi", binaH.ListKisi)
			r.Post("/bina/duyuru", binaH.CreateDuyuru)
			r.Get("/bina/duyuru", binaH.ListDuyuru)
			r.Post("/bina/aidat/hesapla", binaH.AidatHesapla)
			r.Get("/bina/aidat", binaH.ListAidat)
			r.Post("/bina/aidat/{id}/ode", binaH.AidatOdeme)
			r.Post("/bina/gelir", binaH.CreateGelir)
			r.Post("/bina/gider", binaH.CreateGider)
			r.Get("/bina/gelir", binaH.ListGelir)
			r.Get("/bina/gider", binaH.ListGider)
			r.Post("/bina/arac", binaH.CreateArac)
			r.Get("/bina/arac", binaH.ListArac)
			r.Delete("/bina/arac/{id}", binaH.DeleteArac)
			r.Post("/bina/personel", binaH.CreatePersonel)
			r.Get("/bina/personel", binaH.ListPersonel)
			r.Post("/bina/firma", binaH.CreateFirma)
			r.Get("/bina/firma", binaH.ListFirma)
			r.Post("/bina/is-talebi", binaH.CreateIsTalebi)
			r.Get("/bina/is-talebi", binaH.ListIsTalebi)
			r.Post("/bina/sayac", binaH.CreateSayac)
			r.Get("/bina/sayac", binaH.ListSayac)
			r.Post("/bina/kargo", binaH.CreateKargo)
			r.Get("/bina/kargo", binaH.ListKargo)
			r.Post("/bina/ziyaretci", binaH.CreateZiyaretci)
			r.Get("/bina/ziyaretci", binaH.ListZiyaretci)
			r.Post("/bina/ziyaretci/{id}/cikis", binaH.ZiyaretciCikis)

			r.Post("/bina/anket", binaH.CreateAnket)
			r.Get("/bina/anket", binaH.ListAnket)
			r.Get("/bina/anket/{id}", binaH.GetAnket)
			r.Delete("/bina/anket/{id}", binaH.DeleteAnket)
			r.Post("/bina/anket/{id}/oy", binaH.AnketOy)
			r.Post("/bina/anket/{id}/secenek", binaH.CreateAnketSecenek)
			r.Get("/bina/anket/{id}/secenek", binaH.ListAnketSecenek)
			r.Delete("/bina/anket-secenek/{id}", binaH.DeleteAnketSecenek)
			r.Post("/bina/icra", binaH.CreateIcra)
			r.Get("/bina/icra", binaH.ListIcra)
			r.Get("/bina/icra/{id}", binaH.GetIcra)
			r.Delete("/bina/icra/{id}", binaH.DeleteIcra)
			r.Post("/bina/otopark", binaH.CreateOtopark)
			r.Get("/bina/otopark", binaH.ListOtopark)
			r.Get("/bina/otopark/{id}", binaH.GetOtopark)
			r.Delete("/bina/otopark/{id}", binaH.DeleteOtopark)
			r.Post("/bina/rezervasyon", binaH.CreateRezervasyon)
			r.Get("/bina/rezervasyon", binaH.ListRezervasyon)
			r.Get("/bina/rezervasyon/{id}", binaH.GetRezervasyon)
			r.Delete("/bina/rezervasyon/{id}", binaH.DeleteRezervasyon)
			r.Post("/bina/toplanti", binaH.CreateToplanti)
			r.Get("/bina/toplanti", binaH.ListToplanti)
			r.Get("/bina/toplanti/{id}", binaH.GetToplanti)
			r.Delete("/bina/toplanti/{id}", binaH.DeleteToplanti)
			r.Post("/bina/banka", binaH.CreateBanka)
			r.Get("/bina/banka", binaH.ListBanka)
			r.Get("/bina/banka/{id}", binaH.GetBankaHesap)
			r.Delete("/bina/banka/{id}", binaH.DeleteBankaHesap)
			r.Post("/bina/isitma", binaH.CreateIsitma)
			r.Get("/bina/isitma", binaH.ListIsitma)
			r.Get("/bina/isitma/{id}", binaH.GetIsitma)
			r.Delete("/bina/isitma/{id}", binaH.DeleteIsitma)
			r.Post("/bina/butce", binaH.CreateButce)
			r.Get("/bina/butce", binaH.ListButce)
			r.Get("/bina/butce/{id}", binaH.GetButce)
			r.Delete("/bina/butce/{id}", binaH.DeleteButce)
			r.Post("/bina/dosya", binaH.CreateDosya)
			r.Get("/bina/dosya", binaH.ListDosya)
			r.Get("/bina/dosya/{id}", binaH.GetDosya)
			r.Delete("/bina/dosya/{id}", binaH.DeleteDosya)
			r.Post("/bina/bildirim", binaH.CreateBildirim)
			r.Get("/bina/bildirim", binaH.ListBildirim)
			r.Get("/bina/bildirim/{id}", binaH.GetBildirim)
			r.Delete("/bina/bildirim/{id}", binaH.DeleteBildirim)

			// Support / Tickets
			r.Post("/tickets", supportH.Create)
			r.Get("/tickets", supportH.ListMy)
			r.Get("/tickets/admin", supportH.ListAll)
			r.Get("/tickets/{ticket_id}", supportH.Get)
			r.Post("/tickets/{ticket_id}/messages", supportH.AddMessage)
			r.Put("/tickets/{ticket_id}/status", supportH.UpdateStatus)

			// Events / Ticketing
			eventRepo := postgres.NewEventRepo(pool)
			eventH := handler.NewEventHandler(eventRepo)

			r.Post("/events/venues", eventH.CreateVenue)
			r.Get("/events/venues", eventH.ListVenues)
			r.Get("/events/venues/{id}", eventH.GetVenue)
			r.Delete("/events/venues/{id}", eventH.DeleteVenue)
			r.Post("/events/venues/{id}/sections", eventH.CreateVenueSection)
			r.Get("/events/venues/{id}/sections", eventH.ListVenueSections)
			r.Post("/events", eventH.CreateEvent)
			r.Get("/events", eventH.ListEvents)
			r.Get("/events/{id}", eventH.GetEvent)
			r.Put("/events/{id}/status", eventH.UpdateEventStatus)
			r.Delete("/events/{id}", eventH.DeleteEvent)
			r.Post("/events/{id}/sessions", eventH.CreateEventSession)
			r.Get("/events/{id}/sessions", eventH.ListEventSessions)
			r.Post("/events/sessions/{id}/pricing", eventH.CreateSessionPricing)
			r.Get("/events/sessions/{id}/pricing", eventH.ListSessionPricing)
			r.Post("/events/sessions/{id}/seats", eventH.BulkCreateSeats)
			r.Get("/events/sessions/{id}/sections/{sid}/seats/available", eventH.GetAvailableSeats)
			r.Post("/events/bookings", eventH.Reserve)
			r.Get("/events/bookings", eventH.ListUserBookings)
			r.Get("/events/bookings/{id}", eventH.GetTicketBooking)
			r.Post("/events/bookings/{id}/confirm", eventH.ConfirmBooking)
			r.Post("/events/bookings/{id}/cancel", eventH.CancelBooking)

			// Vehicle Catalog
			r.Post("/vehicles/brands", vehicleH.CreateBrand)
			r.Get("/vehicles/brands", vehicleH.ListBrands)
			r.Get("/vehicles/brands/{id}", vehicleH.GetBrand)
			r.Post("/vehicles/brands/{id}/models", vehicleH.CreateModel)
			r.Get("/vehicles/models", vehicleH.ListModels)
			r.Get("/vehicles/models/{id}", vehicleH.GetModel)
			r.Get("/vehicles/categories", vehicleH.ListCategories)
			r.Get("/vehicles/segments", vehicleH.ListSegments)
			r.Get("/vehicles/body-types", vehicleH.ListBodyTypes)
			r.Get("/vehicles/models/{id}/years", vehicleH.ListModelYears)
			r.Get("/vehicles/feature-groups", vehicleH.ListFeatureGroups)
			r.Get("/vehicles/features", vehicleH.ListFeatures)
			r.Post("/vehicles/feature-groups", vehicleH.CreateFeatureGroup)
			r.Post("/vehicles/features", vehicleH.CreateFeature)
			// Vehicle listing routes
			r.Post("/vehicles/listings", vehicleListingH.CreateListing)
			r.Get("/vehicles/listings", vehicleListingH.SearchListings)
			r.Get("/vehicles/listings/{id}", vehicleListingH.GetListing)
			r.Put("/vehicles/listings/{id}", vehicleListingH.UpdateListing)
			r.Post("/vehicles/galleries", vehicleListingH.CreateGallery)

			// Cargo / Shipping
			r.Post("/cargo/companies", cargoH.CreateCompany)
			r.Get("/cargo/companies/me", cargoH.GetMyCompany)
			r.Get("/cargo/companies", cargoH.ListCompanies)
			r.Get("/cargo/companies/{id}", cargoH.GetCompany)
			r.Post("/cargo/shipments", cargoH.CreateShipment)
			r.Get("/cargo/shipments/tracking/{tracking_no}", cargoH.TrackShipment)

			// Expert Inspection
			r.Post("/expert/companies", expertH.CreateCompany)
			r.Get("/expert/companies", expertH.ListCompanies)
			r.Post("/expert/experts", expertH.CreateExpert)
			r.Get("/expert/experts", expertH.ListExperts)
			r.Get("/expert/experts/{id}", expertH.GetExpert)
			r.Post("/expert/packages", expertH.CreatePackage)
			r.Get("/expert/packages", expertH.ListPackages)
			r.Post("/expert/vehicles", expertH.CreateVehicle)
			r.Get("/expert/vehicles", expertH.ListVehicles)
			r.Post("/expert/reports", expertH.CreateReport)
			r.Get("/expert/reports", expertH.ListReports)
			r.Get("/expert/reports/{id}", expertH.GetReport)
			r.Put("/expert/reports/{id}/status", expertH.UpdateReportStatus)
			r.Put("/expert/reports/{id}/approve", expertH.ApproveReport)
			r.Delete("/expert/reports/{id}", expertH.DeleteReport)
			r.Get("/expert/reports/{id}/checks/panel", expertH.GetPanelMeasurements)
			r.Get("/expert/reports/{id}/checks/mechanical", expertH.GetMechanicalChecks)
			r.Get("/expert/reports/{id}/checks/electronic", expertH.GetElectronicChecks)
			r.Get("/expert/reports/{id}/checks/interior", expertH.GetInteriorChecks)
			r.Get("/expert/reports/{id}/checks/exterior", expertH.GetExteriorChecks)
			r.Get("/expert/reports/{id}/checks/tire", expertH.GetTireChecks)
			r.Get("/expert/reports/{id}/checks/emission", expertH.GetEmissionTests)
			r.Get("/expert/reports/{id}/checks/fluid", expertH.GetFluidTests)
			r.Get("/expert/reports/{id}/checks/handbrake", expertH.GetHandbrakeTests)
			r.Get("/expert/reports/{id}/checks/4wd", expertH.GetFourWheelDriveChecks)
			r.Get("/expert/reports/{id}/checks/belt", expertH.GetBeltChecks)
			r.Get("/expert/reports/{id}/checks/chassis", expertH.GetChassisChecks)
			r.Get("/expert/reports/{id}/checks/extra-equipment", expertH.GetExtraEquipment)
			r.Get("/expert/reports/{id}/checks/mandatory-equipment", expertH.GetMandatoryEquipment)
			r.Get("/expert/reports/{id}/checks/dyno", expertH.GetDynoTests)
			r.Get("/expert/reports/{id}/checks/test-drive", expertH.GetTestDrive)
			r.Get("/expert/reports/{id}/checks/tramer", expertH.GetTramerRecord)
			r.Get("/expert/reports/{id}/checks/acceptance-criteria", expertH.GetAcceptanceCriteria)
			r.Put("/expert/reports/{id}/checks/panel", expertH.UpdatePanelMeasurements)
			r.Put("/expert/reports/{id}/checks/mechanical", expertH.UpdateMechanicalChecks)
			r.Put("/expert/reports/{id}/checks/electronic", expertH.UpdateElectronicChecks)
			r.Put("/expert/reports/{id}/checks/interior", expertH.UpdateInteriorChecks)
			r.Put("/expert/reports/{id}/checks/exterior", expertH.UpdateExteriorChecks)
			r.Put("/expert/reports/{id}/checks/tire", expertH.UpdateTireChecks)
			r.Put("/expert/reports/{id}/checks/emission", expertH.UpdateEmissionTests)
			r.Put("/expert/reports/{id}/checks/fluid", expertH.UpdateFluidTests)
			r.Put("/expert/reports/{id}/checks/handbrake", expertH.UpdateHandbrakeTests)
			r.Put("/expert/reports/{id}/checks/4wd", expertH.UpdateFourWheelDriveChecks)
			r.Put("/expert/reports/{id}/checks/belt", expertH.UpdateBeltChecks)
			r.Put("/expert/reports/{id}/checks/chassis", expertH.UpdateChassisChecks)
			r.Put("/expert/reports/{id}/checks/extra-equipment", expertH.UpdateExtraEquipment)
			r.Put("/expert/reports/{id}/checks/mandatory-equipment", expertH.UpdateMandatoryEquipment)
			r.Put("/expert/reports/{id}/checks/dyno", expertH.UpdateDynoTests)
			r.Put("/expert/reports/{id}/checks/test-drive", expertH.UpdateTestDrive)
			r.Put("/expert/reports/{id}/checks/tramer", expertH.UpdateTramerRecord)
			r.Post("/expert/reports/{id}/photos", expertH.CreatePhotos)
			r.Get("/expert/reports/{id}/photos", expertH.ListPhotos)

			// Real Estate
			r.Post("/realestate/categories", realestateH.CreateCategory)
			r.Get("/realestate/categories", realestateH.ListCategories)
			r.Delete("/realestate/categories/{id}", realestateH.DeleteCategory)
			r.Post("/realestate/types", realestateH.CreateType)
			r.Get("/realestate/types", realestateH.ListTypes)
			r.Delete("/realestate/types/{id}", realestateH.DeleteType)
			r.Post("/realestate/contractors", realestateH.CreateCompany)
			r.Get("/realestate/contractors", realestateH.ListCompanies)
			r.Get("/realestate/contractors/{id}", realestateH.GetCompany)
			r.Post("/realestate/contractors/{company_id}/documents", realestateH.UploadCompanyDocument)
			r.Get("/realestate/contractors/{company_id}/documents", realestateH.ListCompanyDocuments)
			r.Post("/realestate/contractors/{company_id}/submit-verification", realestateH.SubmitCompanyForVerification)
			r.Put("/realestate/contractors/{company_id}/verify", realestateH.VerifyCompany)
			r.Put("/realestate/contractors/{company_id}/reject", realestateH.RejectCompanyVerification)
			r.Get("/realestate/admin/pending-companies", realestateH.ListPendingCompanies)
			r.Post("/realestate/reviews", realestateH.CreateReview)
			r.Get("/realestate/reviews/{company_id}", realestateH.ListReviews)
			r.Post("/realestate/listings", realestateH.CreateListing)
			r.Get("/realestate/listings", realestateH.ListListings)
			r.Get("/realestate/listings/search", realestateH.SearchListings)
			r.Get("/realestate/listings/{id}", realestateH.GetListing)
			r.Put("/realestate/listings/{id}", realestateH.UpdateListing)
			r.Delete("/realestate/listings/{id}", realestateH.DeleteListing)
			r.Post("/realestate/listings/{id}/view", realestateH.IncrementViewCount)
			r.Post("/realestate/listings/{id}/photos", realestateH.AddPhoto)
			r.Get("/realestate/listings/{id}/photos", realestateH.ListPhotos)
			r.Delete("/realestate/photos/{id}", realestateH.DeletePhoto)
			r.Put("/realestate/listings/{listing_id}/photos/{photo_id}/cover", realestateH.SetCoverPhoto)
			r.Post("/realestate/features", realestateH.CreateFeature)
			r.Get("/realestate/features", realestateH.ListFeatures)
			r.Post("/realestate/listings/{listing_id}/features", realestateH.AddListingFeatures)
			r.Get("/realestate/listings/{listing_id}/features", realestateH.GetListingFeatures)
			r.Delete("/realestate/listings/{listing_id}/features/{feature_id}", realestateH.RemoveListingFeature)
			r.Post("/realestate/authorizations", realestateH.CreateAuthorization)
			r.Get("/realestate/listings/{listing_id}/authorizations", realestateH.ListAuthorizations)
			r.Put("/realestate/authorizations/{id}/status", realestateH.UpdateAuthorizationStatus)
			r.Post("/realestate/appraisals", realestateH.CreateAppraisalRequest)
			r.Get("/realestate/appraisals/{id}", realestateH.GetAppraisalRequest)
			r.Get("/realestate/appraisals", realestateH.ListAppraisalRequests)
			r.Put("/realestate/appraisals/{id}/status", realestateH.UpdateAppraisalStatus)
			r.Post("/realestate/favorites", realestateH.AddFavorite)
			r.Delete("/realestate/favorites/{user_id}/{listing_id}", realestateH.RemoveFavorite)
			r.Get("/realestate/favorites/{user_id}", realestateH.ListFavorites)
			r.Get("/realestate/favorites/{user_id}/check/{listing_id}", realestateH.IsFavorite)
			r.Post("/realestate/inquiries", realestateH.SendInquiry)
			r.Get("/realestate/listings/{listing_id}/inquiries", realestateH.ListInquiriesByListing)
			r.Get("/realestate/inquiries/{user_id}", realestateH.ListInquiriesByUser)
			r.Put("/realestate/inquiries/{id}/read", realestateH.MarkAsRead)
			r.Post("/realestate/companies/{company_id}/members", realestateH.AddMember)
			r.Get("/realestate/companies/{company_id}/members", realestateH.ListMembers)
			r.Put("/realestate/members/{member_id}", realestateH.UpdateMemberRole)
			r.Delete("/realestate/members/{member_id}", realestateH.RemoveMember)
			r.Post("/realestate/companies/{company_id}/invitations", realestateH.CreateInvitation)
			r.Get("/realestate/companies/{company_id}/invitations", realestateH.ListInvitations)
			r.Put("/realestate/invitations/{id}/accept", realestateH.AcceptInvitation)
			r.Put("/realestate/invitations/{id}/reject", realestateH.RejectInvitation)
			r.Get("/realestate/users/{user_id}/companies", realestateH.ListMyCompanies)
			r.Get("/realestate/pricing", realestateH.GetListingPrice)
			r.Get("/realestate/listings/{id}/benchmark", realestateH.GetRegionBenchmark)
			r.Post("/realestate/listings/{id}/pay", realestateH.PayForListing)
			r.Get("/realestate/payments", realestateH.ListMyPayments)
			r.Post("/realestate/listings/{id}/documents", realestateH.UploadDocument)
			r.Get("/realestate/listings/{id}/documents", realestateH.ListListingDocuments)
			r.Post("/realestate/listings/{id}/submit-verification", realestateH.SubmitForVerification)
			r.Put("/realestate/documents/{doc_id}/verify", realestateH.VerifyDocument)
			r.Put("/realestate/documents/{doc_id}/reject", realestateH.RejectDocument)
			r.Get("/realestate/documents", realestateH.ListMyDocuments)
			// Cicek (Flower) routes
			r.Post("/cicek/florists", cicekH.CreateFlorist)
			r.Get("/cicek/florists/me", cicekH.GetMyFlorist)
			r.Get("/cicek/florists/{id}", cicekH.GetFlorist)
			r.Put("/cicek/florists/{id}", cicekH.UpdateFlorist)
			r.Post("/cicek/florists/{id}/toggle", cicekH.ToggleFlorist)
			r.Post("/cicek/florists/{id}/products", cicekH.CreateProduct)
		})

		r.Get("/cicek/public/florists", cicekH.ListFlorists)
		r.Get("/cicek/public/florists/{slug}", cicekH.GetFloristBySlug)
	})

	r.Get("/health", func(w http.ResponseWriter, r *http.Request) {
		writeJSON(w, http.StatusOK, map[string]string{"status": "ok"})
	})

	return r
}

func writeJSON(w http.ResponseWriter, status int, data interface{}) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	json.NewEncoder(w).Encode(data)
}
