import json, os

MANUAL = {
    "Suzuki": [
        {"model": "Swift", "segment": "B", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2004},
        {"model": "Vitara", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2015},
        {"model": "S-Cross", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2013},
        {"model": "Ignis", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2016},
        {"model": "Jimny", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 1998},
        {"model": "Baleno", "segment": "B", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2016},
        {"model": "Celerio", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2014},
        {"model": "Alto", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2009},
        {"model": "Swace", "segment": "C", "kasa_tipleri": ["Station Wagon"], "uretim_baslangic": 2020},
        {"model": "Grand Vitara", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2022},
        {"model": "Splash", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2008},
        {"model": "Kizashi", "segment": "D", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2009, "uretim_bitis": 2014},
    ],
    "McLaren": [
        {"model": "Artura", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2021},
        {"model": "750S", "segment": "S", "kasa_tipleri": ["Coupe", "Cabrio"], "uretim_baslangic": 2023},
        {"model": "GT", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2019},
        {"model": "Speedtail", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2019},
        {"model": "Senna", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2018},
        {"model": "720S", "segment": "S", "kasa_tipleri": ["Coupe", "Cabrio"], "uretim_baslangic": 2017},
        {"model": "P1", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2013, "uretim_bitis": 2015},
        {"model": "600LT", "segment": "S", "kasa_tipleri": ["Coupe", "Cabrio"], "uretim_baslangic": 2018},
        {"model": "570S", "segment": "S", "kasa_tipleri": ["Coupe", "Cabrio"], "uretim_baslangic": 2015},
        {"model": "540C", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2015},
        {"model": "650S", "segment": "S", "kasa_tipleri": ["Coupe", "Cabrio"], "uretim_baslangic": 2014},
        {"model": "12C", "segment": "S", "kasa_tipleri": ["Coupe", "Cabrio"], "uretim_baslangic": 2011},
        {"model": "F1", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 1992, "uretim_bitis": 1998},
    ],
    "Bugatti": [
        {"model": "Chiron", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2016},
        {"model": "Divo", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2018},
        {"model": "La Voiture Noire", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2019},
        {"model": "Centodieci", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2019},
        {"model": "Bolide", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2021},
        {"model": "Mistral", "segment": "S", "kasa_tipleri": ["Cabrio"], "uretim_baslangic": 2022},
        {"model": "Tourbillon", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2024},
        {"model": "Veyron", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2005, "uretim_bitis": 2015},
    ],
    "Jaguar": [
        {"model": "XE", "segment": "D", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2015},
        {"model": "XF", "segment": "E", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 2007},
        {"model": "XJ", "segment": "F", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2009, "uretim_bitis": 2019},
        {"model": "E-Pace", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2017},
        {"model": "F-Pace", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2016},
        {"model": "I-Pace", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2018},
        {"model": "F-Type", "segment": "S", "kasa_tipleri": ["Coupe", "Cabrio"], "uretim_baslangic": 2013},
        {"model": "XK", "segment": "S", "kasa_tipleri": ["Coupe", "Cabrio"], "uretim_baslangic": 2006, "uretim_bitis": 2014},
        {"model": "S-Type", "segment": "E", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 1999, "uretim_bitis": 2007},
        {"model": "X-Type", "segment": "D", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 2001, "uretim_bitis": 2009},
    ],
    "Tata": [
        {"model": "Nexon", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2017},
        {"model": "Harrier", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2019},
        {"model": "Safari", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2021},
        {"model": "Altroz", "segment": "B", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2020},
        {"model": "Tiago", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2016},
        {"model": "Tigor", "segment": "B", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2017},
        {"model": "Punch", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2021},
        {"model": "Curvv", "segment": "J", "kasa_tipleri": ["Coupe", "SUV"], "uretim_baslangic": 2024},
    ],
    "Ram": [
        {"model": "1500", "segment": "P", "kasa_tipleri": ["Pick-up"], "uretim_baslangic": 2009},
        {"model": "2500", "segment": "P", "kasa_tipleri": ["Pick-up"], "uretim_baslangic": 2010},
        {"model": "3500", "segment": "P", "kasa_tipleri": ["Pick-up"], "uretim_baslangic": 2010},
        {"model": "ProMaster", "segment": "V", "kasa_tipleri": ["Van"], "uretim_baslangic": 2013},
        {"model": "ProMaster City", "segment": "V", "kasa_tipleri": ["Van"], "uretim_baslangic": 2015},
    ],
    "Rimac": [
        {"model": "Nevera", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2021},
        {"model": "Concept_One", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2013, "uretim_bitis": 2016},
    ],
    "BMW": [
        {"model": "1 Serisi", "segment": "C", "kasa_tipleri": ["Hatchback", "Sedan"], "uretim_baslangic": 2004},
        {"model": "2 Serisi", "segment": "C", "kasa_tipleri": ["Coupe", "Cabrio", "Gran Coupe"], "uretim_baslangic": 2014},
        {"model": "3 Serisi", "segment": "D", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 1975},
        {"model": "4 Serisi", "segment": "D", "kasa_tipleri": ["Coupe", "Cabrio", "Gran Coupe"], "uretim_baslangic": 2013},
        {"model": "5 Serisi", "segment": "E", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 1972},
        {"model": "6 Serisi", "segment": "E", "kasa_tipleri": ["Coupe", "Cabrio", "Gran Coupe"], "uretim_baslangic": 2011},
        {"model": "7 Serisi", "segment": "F", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 1977},
        {"model": "8 Serisi", "segment": "F", "kasa_tipleri": ["Coupe", "Cabrio", "Gran Coupe"], "uretim_baslangic": 2018},
        {"model": "X1", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2009},
        {"model": "X2", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2017},
        {"model": "X3", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2003},
        {"model": "X4", "segment": "J", "kasa_tipleri": ["Coupe", "SUV"], "uretim_baslangic": 2014},
        {"model": "X5", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 1999},
        {"model": "X6", "segment": "J", "kasa_tipleri": ["Coupe", "SUV"], "uretim_baslangic": 2008},
        {"model": "X7", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2018},
        {"model": "XM", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2022},
        {"model": "Z4", "segment": "S", "kasa_tipleri": ["Cabrio"], "uretim_baslangic": 2002},
        {"model": "i4", "segment": "D", "kasa_tipleri": ["Gran Coupe"], "uretim_baslangic": 2021},
        {"model": "i5", "segment": "E", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 2023},
        {"model": "i7", "segment": "F", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2022},
        {"model": "iX", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2021},
        {"model": "iX1", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2022},
        {"model": "iX3", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2020},
        {"model": "M2", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2015},
        {"model": "M3", "segment": "S", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 1986},
        {"model": "M4", "segment": "S", "kasa_tipleri": ["Coupe", "Cabrio"], "uretim_baslangic": 2014},
        {"model": "M5", "segment": "S", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 1984},
        {"model": "M8", "segment": "S", "kasa_tipleri": ["Coupe", "Cabrio"], "uretim_baslangic": 2019},
        {"model": "X3 M", "segment": "S", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2019},
        {"model": "X4 M", "segment": "S", "kasa_tipleri": ["Coupe", "SUV"], "uretim_baslangic": 2019},
        {"model": "X5 M", "segment": "S", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2009},
        {"model": "X6 M", "segment": "S", "kasa_tipleri": ["Coupe", "SUV"], "uretim_baslangic": 2009},
        {"model": "i3", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2013, "uretim_bitis": 2022},
        {"model": "i8", "segment": "S", "kasa_tipleri": ["Coupe", "Cabrio"], "uretim_baslangic": 2014, "uretim_bitis": 2020},
    ],
    "Mercedes-Benz": [
        {"model": "A Serisi", "segment": "C", "kasa_tipleri": ["Hatchback", "Sedan"], "uretim_baslangic": 1997},
        {"model": "B Serisi", "segment": "C", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2005},
        {"model": "C Serisi", "segment": "D", "kasa_tipleri": ["Sedan", "Station Wagon", "Coupe", "Cabrio"], "uretim_baslangic": 1993},
        {"model": "CLA", "segment": "C", "kasa_tipleri": ["Coupe", "Station Wagon"], "uretim_baslangic": 2013},
        {"model": "CLS", "segment": "E", "kasa_tipleri": ["Coupe", "Station Wagon"], "uretim_baslangic": 2004},
        {"model": "E Serisi", "segment": "E", "kasa_tipleri": ["Sedan", "Station Wagon", "Coupe", "Cabrio"], "uretim_baslangic": 1993},
        {"model": "S Serisi", "segment": "F", "kasa_tipleri": ["Sedan", "Coupe", "Cabrio"], "uretim_baslangic": 1972},
        {"model": "GLA", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2013},
        {"model": "GLB", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2019},
        {"model": "GLC", "segment": "J", "kasa_tipleri": ["SUV", "Coupe"], "uretim_baslangic": 2015},
        {"model": "GLE", "segment": "J", "kasa_tipleri": ["SUV", "Coupe"], "uretim_baslangic": 2015},
        {"model": "GLS", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2015},
        {"model": "G Serisi", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 1979},
        {"model": "EQA", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2021},
        {"model": "EQB", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2021},
        {"model": "EQC", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2019},
        {"model": "EQE", "segment": "E", "kasa_tipleri": ["Sedan", "SUV"], "uretim_baslangic": 2022},
        {"model": "EQS", "segment": "F", "kasa_tipleri": ["Sedan", "SUV"], "uretim_baslangic": 2021},
        {"model": "EQV", "segment": "M", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2020},
        {"model": "AMG GT", "segment": "S", "kasa_tipleri": ["Coupe", "Cabrio"], "uretim_baslangic": 2014},
        {"model": "AMG SL", "segment": "S", "kasa_tipleri": ["Cabrio"], "uretim_baslangic": 2021},
        {"model": "AMG One", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2022},
        {"model": "V Serisi", "segment": "M", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2014},
        {"model": "Citan", "segment": "V", "kasa_tipleri": ["Van"], "uretim_baslangic": 2012},
        {"model": "Sprinter", "segment": "V", "kasa_tipleri": ["Van"], "uretim_baslangic": 1995},
        {"model": "SL", "segment": "S", "kasa_tipleri": ["Cabrio"], "uretim_baslangic": 2001, "uretim_bitis": 2020},
        {"model": "SLC", "segment": "S", "kasa_tipleri": ["Cabrio"], "uretim_baslangic": 2016, "uretim_bitis": 2020},
        {"model": "CLK", "segment": "D", "kasa_tipleri": ["Coupe", "Cabrio"], "uretim_baslangic": 1997, "uretim_bitis": 2009},
        {"model": "CLC", "segment": "C", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2008, "uretim_bitis": 2011},
    ],
    "Volkswagen": [
        {"model": "Golf", "segment": "C", "kasa_tipleri": ["Hatchback", "Station Wagon"], "uretim_baslangic": 1974},
        {"model": "Passat", "segment": "D", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 1973},
        {"model": "Polo", "segment": "B", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 1975},
        {"model": "Tiguan", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2007},
        {"model": "T-Roc", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2017},
        {"model": "T-Cross", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2019},
        {"model": "Taigo", "segment": "J", "kasa_tipleri": ["Coupe", "SUV"], "uretim_baslangic": 2021},
        {"model": "ID.3", "segment": "C", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2020},
        {"model": "ID.4", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2020},
        {"model": "ID.5", "segment": "J", "kasa_tipleri": ["Coupe", "SUV"], "uretim_baslangic": 2021},
        {"model": "ID.6", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2021},
        {"model": "ID.7", "segment": "E", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 2023},
        {"model": "ID.Buzz", "segment": "M", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2022},
        {"model": "Arteon", "segment": "D", "kasa_tipleri": ["Coupe", "Station Wagon"], "uretim_baslangic": 2017},
        {"model": "Touran", "segment": "M", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2003},
        {"model": "Sharan", "segment": "M", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2010},
        {"model": "Caddy", "segment": "V", "kasa_tipleri": ["Van", "MPV"], "uretim_baslangic": 2003},
        {"model": "Multivan", "segment": "M", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2003},
        {"model": "California", "segment": "M", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2004},
        {"model": "Amarok", "segment": "P", "kasa_tipleri": ["Pick-up"], "uretim_baslangic": 2010},
        {"model": "Touareg", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2002},
        {"model": "Up!", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2011},
        {"model": "Lupo", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 1998, "uretim_bitis": 2005},
        {"model": "Fox", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2004, "uretim_bitis": 2011},
        {"model": "Beetle", "segment": "C", "kasa_tipleri": ["Coupe", "Cabrio"], "uretim_baslangic": 2011, "uretim_bitis": 2019},
        {"model": "Eos", "segment": "C", "kasa_tipleri": ["Cabrio"], "uretim_baslangic": 2006, "uretim_bitis": 2015},
        {"model": "Scirocco", "segment": "C", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2008, "uretim_bitis": 2017},
        {"model": "Phaeton", "segment": "F", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2003, "uretim_bitis": 2016},
        {"model": "Jetta", "segment": "C", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 1979},
        {"model": "Vento", "segment": "C", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2011, "uretim_bitis": 2018},
        {"model": "Santana", "segment": "D", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2012},
        {"model": "Lavida", "segment": "C", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2008},
    ],
    "Honda": [
        {"model": "Civic", "segment": "C", "kasa_tipleri": ["Sedan", "Hatchback"], "uretim_baslangic": 1972},
        {"model": "Accord", "segment": "D", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 1976},
        {"model": "CR-V", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 1995},
        {"model": "HR-V", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2014},
        {"model": "Jazz / Fit", "segment": "B", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2001},
        {"model": "City", "segment": "B", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2008},
        {"model": "Insight", "segment": "C", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2018},
        {"model": "e:Ny1", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2023},
        {"model": "Prologue", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2024},
        {"model": "CR-Z", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2010, "uretim_bitis": 2016},
        {"model": "S2000", "segment": "S", "kasa_tipleri": ["Cabrio"], "uretim_baslangic": 1999, "uretim_bitis": 2009},
        {"model": "NSX", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2016, "uretim_bitis": 2022},
        {"model": "e", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2020, "uretim_bitis": 2024},
        {"model": "Legend", "segment": "F", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 1985, "uretim_bitis": 2012},
        {"model": "Pilot", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2002},
        {"model": "Ridgeline", "segment": "P", "kasa_tipleri": ["Pick-up"], "uretim_baslangic": 2005},
        {"model": "Odyssey", "segment": "M", "kasa_tipleri": ["MPV"], "uretim_baslangic": 1994},
    ],
    "Fiat": [
        {"model": "500", "segment": "A", "kasa_tipleri": ["Hatchback", "Cabrio"], "uretim_baslangic": 2007},
        {"model": "500X", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2014},
        {"model": "500L", "segment": "C", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2012},
        {"model": "Panda", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2011},
        {"model": "Punto", "segment": "B", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2005, "uretim_bitis": 2018},
        {"model": "Tipo", "segment": "C", "kasa_tipleri": ["Sedan", "Hatchback", "Station Wagon"], "uretim_baslangic": 2015},
        {"model": "Egea", "segment": "C", "kasa_tipleri": ["Sedan", "Hatchback", "Station Wagon"], "uretim_baslangic": 2015},
        {"model": "Doblo", "segment": "M", "kasa_tipleri": ["MPV", "Van"], "uretim_baslangic": 2010},
        {"model": "Fiorino", "segment": "V", "kasa_tipleri": ["Van"], "uretim_baslangic": 2007},
        {"model": "Ducato", "segment": "V", "kasa_tipleri": ["Van"], "uretim_baslangic": 2006},
        {"model": "Talento", "segment": "V", "kasa_tipleri": ["Van"], "uretim_baslangic": 2016},
        {"model": "Fullback", "segment": "P", "kasa_tipleri": ["Pick-up"], "uretim_baslangic": 2016, "uretim_bitis": 2019},
        {"model": "124 Spider", "segment": "S", "kasa_tipleri": ["Cabrio"], "uretim_baslangic": 2016, "uretim_bitis": 2019},
        {"model": "Bravo", "segment": "C", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2007, "uretim_bitis": 2014},
        {"model": "Multipla", "segment": "M", "kasa_tipleri": ["MPV"], "uretim_baslangic": 1998, "uretim_bitis": 2010},
        {"model": "Idea", "segment": "B", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2003, "uretim_bitis": 2012},
        {"model": "Linea", "segment": "C", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2007, "uretim_bitis": 2018},
        {"model": "Sedici", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2006, "uretim_bitis": 2014},
        {"model": "Stilo", "segment": "C", "kasa_tipleri": ["Hatchback", "Station Wagon"], "uretim_baslangic": 2001, "uretim_bitis": 2010},
        {"model": "600", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2023},
        {"model": "Topolino", "segment": "A", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2023},
        {"model": "Grande Panda", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2024},
    ],
    "Opel": [
        {"model": "Corsa", "segment": "B", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 1982},
        {"model": "Astra", "segment": "C", "kasa_tipleri": ["Hatchback", "Station Wagon"], "uretim_baslangic": 1991},
        {"model": "Insignia", "segment": "D", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 2008},
        {"model": "Mokka", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2012},
        {"model": "Crossland", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2017},
        {"model": "Grandland", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2017},
        {"model": "Combo", "segment": "V", "kasa_tipleri": ["Van", "MPV"], "uretim_baslangic": 2011},
        {"model": "Vivaro", "segment": "V", "kasa_tipleri": ["Van"], "uretim_baslangic": 2014},
        {"model": "Movano", "segment": "V", "kasa_tipleri": ["Van"], "uretim_baslangic": 2010},
        {"model": "Zafira", "segment": "M", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2015},
        {"model": "Adam", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2012, "uretim_bitis": 2019},
        {"model": "Karl", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2014, "uretim_bitis": 2019},
        {"model": "Ampera", "segment": "C", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2011, "uretim_bitis": 2015},
        {"model": "Ampera-e", "segment": "B", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2017, "uretim_bitis": 2019},
        {"model": "Cascada", "segment": "D", "kasa_tipleri": ["Cabrio"], "uretim_baslangic": 2013, "uretim_bitis": 2019},
        {"model": "Meriva", "segment": "B", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2010, "uretim_bitis": 2017},
        {"model": "Antara", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2006, "uretim_bitis": 2015},
        {"model": "Frontera", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2024},
        {"model": "Grandland GSe", "segment": "S", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2022},
    ],
    "Peugeot": [
        {"model": "108", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2014},
        {"model": "208", "segment": "B", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2012},
        {"model": "308", "segment": "C", "kasa_tipleri": ["Hatchback", "Station Wagon"], "uretim_baslangic": 2007},
        {"model": "408", "segment": "D", "kasa_tipleri": ["Coupe", "SUV"], "uretim_baslangic": 2022},
        {"model": "508", "segment": "D", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 2018},
        {"model": "2008", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2013},
        {"model": "3008", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2009},
        {"model": "5008", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2017},
        {"model": "Rifter", "segment": "M", "kasa_tipleri": ["MPV", "Van"], "uretim_baslangic": 2018},
        {"model": "Traveler", "segment": "M", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2015},
        {"model": "Boxer", "segment": "V", "kasa_tipleri": ["Van"], "uretim_baslangic": 2006},
        {"model": "Expert", "segment": "V", "kasa_tipleri": ["Van"], "uretim_baslangic": 2016},
        {"model": "Partner", "segment": "V", "kasa_tipleri": ["Van"], "uretim_baslangic": 2018},
        {"model": "e-208", "segment": "B", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2019},
        {"model": "e-308", "segment": "C", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2021},
        {"model": "e-2008", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2019},
        {"model": "RCZ", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2010, "uretim_bitis": 2015},
        {"model": "iOn", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2010, "uretim_bitis": 2020},
        {"model": "107", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2005, "uretim_bitis": 2014},
        {"model": "207", "segment": "B", "kasa_tipleri": ["Hatchback", "Sedan"], "uretim_baslangic": 2006, "uretim_bitis": 2014},
        {"model": "307", "segment": "C", "kasa_tipleri": ["Hatchback", "Station Wagon"], "uretim_baslangic": 2001, "uretim_bitis": 2008},
        {"model": "407", "segment": "D", "kasa_tipleri": ["Sedan", "Station Wagon", "Coupe"], "uretim_baslangic": 2004, "uretim_bitis": 2011},
        {"model": "607", "segment": "E", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2000, "uretim_bitis": 2010},
    ],
    "Škoda": [
        {"model": "Fabia", "segment": "B", "kasa_tipleri": ["Hatchback", "Station Wagon"], "uretim_baslangic": 1999},
        {"model": "Scala", "segment": "C", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2019},
        {"model": "Octavia", "segment": "C", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 1996},
        {"model": "Superb", "segment": "D", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 2001},
        {"model": "Kamiq", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2019},
        {"model": "Karoq", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2017},
        {"model": "Kodiaq", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2016},
        {"model": "Enyaq iV", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2020},
        {"model": "Enyaq Coupe", "segment": "J", "kasa_tipleri": ["Coupe", "SUV"], "uretim_baslangic": 2022},
        {"model": "Citigo", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2011, "uretim_bitis": 2020},
        {"model": "Rapid", "segment": "C", "kasa_tipleri": ["Sedan", "Hatchback"], "uretim_baslangic": 2012, "uretim_bitis": 2020},
        {"model": "Yeti", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2009, "uretim_bitis": 2017},
        {"model": "Roomster", "segment": "M", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2006, "uretim_bitis": 2015},
    ],
    "Renault": [
        {"model": "Clio", "segment": "B", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 1990},
        {"model": "Captur", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2013},
        {"model": "Megane", "segment": "C", "kasa_tipleri": ["Hatchback", "Sedan", "Station Wagon"], "uretim_baslangic": 1995},
        {"model": "Talisman", "segment": "D", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 2015},
        {"model": "Arkana", "segment": "J", "kasa_tipleri": ["Coupe", "SUV"], "uretim_baslangic": 2020},
        {"model": "Austral", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2022},
        {"model": "Rafale", "segment": "J", "kasa_tipleri": ["Coupe", "SUV"], "uretim_baslangic": 2023},
        {"model": "Symbioz", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2024},
        {"model": "Kadjar", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2015, "uretim_bitis": 2022},
        {"model": "Koleos", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2008},
        {"model": "Espace", "segment": "M", "kasa_tipleri": ["MPV", "SUV"], "uretim_baslangic": 2015},
        {"model": "Scenic", "segment": "M", "kasa_tipleri": ["MPV", "SUV"], "uretim_baslangic": 2016},
        {"model": "Zoe", "segment": "B", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2012, "uretim_bitis": 2024},
        {"model": "Twizy", "segment": "A", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2012},
        {"model": "Kangoo", "segment": "V", "kasa_tipleri": ["Van", "MPV"], "uretim_baslangic": 2021},
        {"model": "Trafic", "segment": "V", "kasa_tipleri": ["Van"], "uretim_baslangic": 2014},
        {"model": "Master", "segment": "V", "kasa_tipleri": ["Van"], "uretim_baslangic": 2010},
        {"model": "5 E-Tech", "segment": "B", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2024},
        {"model": "Scenic E-Tech", "segment": "C", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2024},
        {"model": "Laguna", "segment": "D", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 2001, "uretim_bitis": 2015},
        {"model": "Fluence", "segment": "C", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2009, "uretim_bitis": 2016},
        {"model": "Modus", "segment": "B", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2004, "uretim_bitis": 2012},
        {"model": "Wind", "segment": "S", "kasa_tipleri": ["Cabrio"], "uretim_baslangic": 2010, "uretim_bitis": 2013},
    ],
    "Citroën": [
        {"model": "C1", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2014},
        {"model": "C3", "segment": "B", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2002},
        {"model": "C3 Aircross", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2017},
        {"model": "C4", "segment": "C", "kasa_tipleri": ["Hatchback", "Coupe"], "uretim_baslangic": 2020},
        {"model": "C4 X", "segment": "C", "kasa_tipleri": ["Sedan", "Coupe"], "uretim_baslangic": 2022},
        {"model": "C5 Aircross", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2017},
        {"model": "C5 X", "segment": "D", "kasa_tipleri": ["Station Wagon"], "uretim_baslangic": 2021},
        {"model": "C6", "segment": "E", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2016},
        {"model": "e-C3", "segment": "B", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2023},
        {"model": "e-C4", "segment": "C", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2021},
        {"model": "Berlingo", "segment": "M", "kasa_tipleri": ["MPV", "Van"], "uretim_baslangic": 2018},
        {"model": "SpaceTourer", "segment": "M", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2016},
        {"model": "Jumpy", "segment": "V", "kasa_tipleri": ["Van"], "uretim_baslangic": 2016},
        {"model": "Jumper", "segment": "V", "kasa_tipleri": ["Van"], "uretim_baslangic": 2006},
        {"model": "Ami", "segment": "A", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2020},
        {"model": "DS 3", "segment": "B", "kasa_tipleri": ["Hatchback", "SUV"], "uretim_baslangic": 2010, "uretim_bitis": 2019},
        {"model": "DS 4", "segment": "C", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2011, "uretim_bitis": 2018},
        {"model": "DS 7", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2017, "uretim_bitis": 2019},
        {"model": "C3 Picasso", "segment": "B", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2008, "uretim_bitis": 2017},
        {"model": "C4 Picasso", "segment": "C", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2013, "uretim_bitis": 2020},
        {"model": "Grand C4 Picasso", "segment": "C", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2013, "uretim_bitis": 2020},
        {"model": "Xsara Picasso", "segment": "C", "kasa_tipleri": ["MPV"], "uretim_baslangic": 1999, "uretim_bitis": 2012},
    ],
    "Lexus": [
        {"model": "IS", "segment": "D", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 1998},
        {"model": "ES", "segment": "E", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 1989},
        {"model": "LS", "segment": "F", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 1989},
        {"model": "RC", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2014},
        {"model": "LC", "segment": "S", "kasa_tipleri": ["Coupe", "Cabrio"], "uretim_baslangic": 2017},
        {"model": "UX", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2018},
        {"model": "NX", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2014},
        {"model": "RX", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 1997},
        {"model": "RZ", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2022},
        {"model": "LX", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 1995},
        {"model": "GX", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2002},
        {"model": "LBX", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2023},
        {"model": "TX", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2023},
        {"model": "LFA", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2010, "uretim_bitis": 2012},
        {"model": "CT", "segment": "C", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2011, "uretim_bitis": 2022},
        {"model": "GS", "segment": "E", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 1991, "uretim_bitis": 2020},
        {"model": "SC", "segment": "S", "kasa_tipleri": ["Coupe", "Cabrio"], "uretim_baslangic": 2001, "uretim_bitis": 2010},
    ],
    "Mazda": [
        {"model": "Mazda2", "segment": "B", "kasa_tipleri": ["Hatchback", "Sedan"], "uretim_baslangic": 2014},
        {"model": "Mazda3", "segment": "C", "kasa_tipleri": ["Hatchback", "Sedan"], "uretim_baslangic": 2003},
        {"model": "Mazda6", "segment": "D", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 2002},
        {"model": "CX-3", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2015},
        {"model": "CX-30", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2019},
        {"model": "CX-5", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2012},
        {"model": "CX-50", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2022},
        {"model": "CX-60", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2022},
        {"model": "CX-70", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2024},
        {"model": "CX-80", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2024},
        {"model": "CX-90", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2023},
        {"model": "MX-5", "segment": "S", "kasa_tipleri": ["Cabrio"], "uretim_baslangic": 2015},
        {"model": "MX-30", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2020},
        {"model": "BT-50", "segment": "P", "kasa_tipleri": ["Pick-up"], "uretim_baslangic": 2020},
    ],
    "Mitsubishi": [
        {"model": "Mirage / Space Star", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2012},
        {"model": "ASX", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2010},
        {"model": "Eclipse Cross", "segment": "J", "kasa_tipleri": ["Coupe", "SUV"], "uretim_baslangic": 2017},
        {"model": "Outlander", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2005},
        {"model": "Pajero / Montero", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2006, "uretim_bitis": 2021},
        {"model": "L200", "segment": "P", "kasa_tipleri": ["Pick-up"], "uretim_baslangic": 2015},
        {"model": "Colt", "segment": "B", "kasa_tipleri": ["Hatchback", "Sedan"], "uretim_baslangic": 2002, "uretim_bitis": 2013},
        {"model": "Lancer", "segment": "C", "kasa_tipleri": ["Sedan", "Hatchback"], "uretim_baslangic": 2007, "uretim_bitis": 2017},
        {"model": "Lancer Evo", "segment": "S", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2007, "uretim_bitis": 2016},
        {"model": "i-MiEV", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2009, "uretim_bitis": 2020},
        {"model": "Grandis", "segment": "M", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2003, "uretim_bitis": 2011},
    ],
    "Subaru": [
        {"model": "Impreza", "segment": "C", "kasa_tipleri": ["Sedan", "Hatchback"], "uretim_baslangic": 2016},
        {"model": "WRX", "segment": "D", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2014},
        {"model": "Legacy", "segment": "D", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 2010, "uretim_bitis": 2020},
        {"model": "Outback", "segment": "J", "kasa_tipleri": ["Station Wagon"], "uretim_baslangic": 2014},
        {"model": "Forester", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2012},
        {"model": "Crosstrek / XV", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2018},
        {"model": "Solterra", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2022},
        {"model": "BRZ", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2021},
        {"model": "Levorg", "segment": "D", "kasa_tipleri": ["Station Wagon"], "uretim_baslangic": 2020},
        {"model": "Ascent", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2018},
    ],
    "Porsche": [
        {"model": "718", "segment": "S", "kasa_tipleri": ["Coupe", "Cabrio"], "uretim_baslangic": 2016},
        {"model": "911", "segment": "S", "kasa_tipleri": ["Coupe", "Cabrio", "Targa"], "uretim_baslangic": 2018},
        {"model": "Taycan", "segment": "S", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 2019},
        {"model": "Panamera", "segment": "F", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 2016},
        {"model": "Macan", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2014},
        {"model": "Cayenne", "segment": "J", "kasa_tipleri": ["SUV", "Coupe"], "uretim_baslangic": 2017},
        {"model": "Cayenne Coupe", "segment": "J", "kasa_tipleri": ["Coupe", "SUV"], "uretim_baslangic": 2019},
        {"model": "Carrera GT", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2003, "uretim_bitis": 2006},
        {"model": "918 Spyder", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2013, "uretim_bitis": 2015},
    ],
    "Jeep": [
        {"model": "Compass", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2016},
        {"model": "Cherokee", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2014, "uretim_bitis": 2023},
        {"model": "Grand Cherokee", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2010},
        {"model": "Wrangler", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2017},
        {"model": "Renegade", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2014},
        {"model": "Avenger", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2023},
        {"model": "Gladiator", "segment": "P", "kasa_tipleri": ["Pick-up"], "uretim_baslangic": 2019},
        {"model": "Commander", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2021, "uretim_bitis": 2023},
        {"model": "Wagoneer", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2021},
        {"model": "Grand Wagoneer", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2021},
        {"model": "Compass (KK)", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2006, "uretim_bitis": 2010},
        {"model": "Liberty", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2001, "uretim_bitis": 2012},
    ],
    "Dacia": [
        {"model": "Sandero", "segment": "B", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2012},
        {"model": "Logan", "segment": "B", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 2012},
        {"model": "Duster", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2017},
        {"model": "Jogger", "segment": "M", "kasa_tipleri": ["MPV", "Station Wagon"], "uretim_baslangic": 2021},
        {"model": "Spring", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2021},
        {"model": "Bigster", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2024},
        {"model": "Lodgy", "segment": "M", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2012, "uretim_bitis": 2021},
        {"model": "Dokker", "segment": "V", "kasa_tipleri": ["Van"], "uretim_baslangic": 2012, "uretim_bitis": 2021},
    ],
    "SEAT": [
        {"model": "Ibiza", "segment": "B", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2017},
        {"model": "Leon", "segment": "C", "kasa_tipleri": ["Hatchback", "Station Wagon"], "uretim_baslangic": 2012},
        {"model": "Arona", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2017},
        {"model": "Ateca", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2016},
        {"model": "Tarraco", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2018},
        {"model": "Alhambra", "segment": "M", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2010, "uretim_bitis": 2020},
        {"model": "Mii", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2011, "uretim_bitis": 2020},
        {"model": "Toledo", "segment": "C", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2012, "uretim_bitis": 2019},
        {"model": "Altea", "segment": "C", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2004, "uretim_bitis": 2015},
    ],
    "Mini": [
        {"model": "Cooper", "segment": "B", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2014},
        {"model": "Cooper S", "segment": "B", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2014},
        {"model": "Clubman", "segment": "B", "kasa_tipleri": ["Station Wagon"], "uretim_baslangic": 2015},
        {"model": "Countryman", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2017},
        {"model": "Convertible", "segment": "B", "kasa_tipleri": ["Cabrio"], "uretim_baslangic": 2015},
        {"model": "John Cooper Works", "segment": "S", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2015},
        {"model": "Aceman", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2024},
        {"model": "Paceman", "segment": "J", "kasa_tipleri": ["Coupe", "SUV"], "uretim_baslangic": 2012, "uretim_bitis": 2016},
        {"model": "Coupe", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2011, "uretim_bitis": 2015},
        {"model": "Roadster", "segment": "S", "kasa_tipleri": ["Cabrio"], "uretim_baslangic": 2012, "uretim_bitis": 2015},
    ],
    "Acura": [
        {"model": "Integra", "segment": "C", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2022},
        {"model": "TLX", "segment": "D", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2020},
        {"model": "RLX", "segment": "E", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2013, "uretim_bitis": 2020},
        {"model": "RDX", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2018},
        {"model": "MDX", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2021},
        {"model": "ZDX", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2024},
        {"model": "NSX", "segment": "S", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2016, "uretim_bitis": 2022},
    ],
    "Infiniti": [
        {"model": "Q50", "segment": "D", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2013},
        {"model": "Q60", "segment": "D", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2016},
        {"model": "QX50", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2017},
        {"model": "QX55", "segment": "J", "kasa_tipleri": ["Coupe", "SUV"], "uretim_baslangic": 2021},
        {"model": "QX60", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2021},
        {"model": "QX80", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2024},
        {"model": "Q70", "segment": "E", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2014, "uretim_bitis": 2019},
        {"model": "QX30", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2016, "uretim_bitis": 2019},
    ],
    "Buick": [
        {"model": "Encore", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2012},
        {"model": "Encore GX", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2019},
        {"model": "Envision", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2014},
        {"model": "Enclave", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2007},
        {"model": "LaCrosse", "segment": "E", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2016, "uretim_bitis": 2019},
        {"model": "Regal", "segment": "D", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 2017, "uretim_bitis": 2020},
        {"model": "GL8", "segment": "M", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2016},
        {"model": "Electra", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2024},
    ],
    "Cadillac": [
        {"model": "CT4", "segment": "D", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2019},
        {"model": "CT5", "segment": "E", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2019},
        {"model": "XT4", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2018},
        {"model": "XT5", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2016},
        {"model": "XT6", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2019},
        {"model": "Escalade", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2020},
        {"model": "Lyriq", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2022},
        {"model": "Celestiq", "segment": "F", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2023},
        {"model": "ELR", "segment": "C", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2013, "uretim_bitis": 2016},
        {"model": "ATS", "segment": "D", "kasa_tipleri": ["Sedan", "Coupe"], "uretim_baslangic": 2012, "uretim_bitis": 2019},
        {"model": "CTS", "segment": "E", "kasa_tipleri": ["Sedan", "Coupe", "Station Wagon"], "uretim_baslangic": 2014, "uretim_bitis": 2019},
    ],
    "GMC": [
        {"model": "Terrain", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2017},
        {"model": "Acadia", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2016},
        {"model": "Yukon", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2021},
        {"model": "Sierra 1500", "segment": "P", "kasa_tipleri": ["Pick-up"], "uretim_baslangic": 2019},
        {"model": "Sierra HD", "segment": "P", "kasa_tipleri": ["Pick-up"], "uretim_baslangic": 2020},
        {"model": "Hummer EV", "segment": "P", "kasa_tipleri": ["Pick-up", "SUV"], "uretim_baslangic": 2022},
        {"model": "Canyon", "segment": "P", "kasa_tipleri": ["Pick-up"], "uretim_baslangic": 2023},
        {"model": "Savana", "segment": "V", "kasa_tipleri": ["Van"], "uretim_baslangic": 2020},
    ],
    "MG": [
        {"model": "MG3", "segment": "B", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2024},
        {"model": "MG4", "segment": "C", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2022},
        {"model": "MG5", "segment": "C", "kasa_tipleri": ["Station Wagon"], "uretim_baslangic": 2022},
        {"model": "MG6", "segment": "D", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2021},
        {"model": "MG ZS", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2017},
        {"model": "MG HS", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2018},
        {"model": "MG EHS", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2020},
        {"model": "MG Marvel R", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2021},
        {"model": "MG Cyberster", "segment": "S", "kasa_tipleri": ["Cabrio"], "uretim_baslangic": 2023},
        {"model": "MG One", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2021},
    ],
    "Perodua": [
        {"model": "Myvi", "segment": "B", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2005},
        {"model": "Axia", "segment": "A", "kasa_tipleri": ["Hatchback"], "uretim_baslangic": 2014},
        {"model": "Bezza", "segment": "B", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2016},
        {"model": "Alza", "segment": "M", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2022},
        {"model": "Aruz", "segment": "M", "kasa_tipleri": ["MPV"], "uretim_baslangic": 2019},
        {"model": "Ativa", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2020},
    ],
    "Genesis": [
        {"model": "G70", "segment": "D", "kasa_tipleri": ["Sedan", "Station Wagon"], "uretim_baslangic": 2017},
        {"model": "G80", "segment": "E", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2016},
        {"model": "G90", "segment": "F", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2016},
        {"model": "GV60", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2021},
        {"model": "GV70", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2020},
        {"model": "GV80", "segment": "J", "kasa_tipleri": ["SUV"], "uretim_baslangic": 2020},
        {"model": "Electrified G80", "segment": "E", "kasa_tipleri": ["Sedan"], "uretim_baslangic": 2021},
        {"model": "Mint", "segment": "B", "kasa_tipleri": ["Coupe"], "uretim_baslangic": 2019},
    ],
}

for brand, models in MANUAL.items():
    dosya_adi = brand.lower().replace(" ", "_").replace("\u00fc", "u").replace("\u00f6", "o").replace("\u0131", "i").replace("\u015f", "s").replace("\u00e7", "c").replace("\u011f", "g")
    dosya = {"marka": brand, "modeller": models, "kaynak": "manuel"}
    with open(os.path.join("modeller", f"{dosya_adi}.json"), "w", encoding="utf-8") as f:
        json.dump(dosya, f, ensure_ascii=False, indent=2)
    print(f"{brand}: {len(models)} model guncellendi")
