-- ============================================================
-- MESLEKLER VERiTABANI - PostgreSQL
-- ============================================================

-- Once mevcut veritabanini silip olustur
DROP DATABASE IF EXISTS meslekler;
CREATE DATABASE meslekler;
\c meslekler;

-- Kategoriler tablosu
CREATE TABLE categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    emoji VARCHAR(10),
    sort_order INT NOT NULL
);

-- Meslekler tablosu
CREATE TABLE professions (
    id SERIAL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    category_id INT NOT NULL REFERENCES categories(id) ON DELETE CASCADE
);

CREATE INDEX idx_professions_category ON professions(category_id);
CREATE INDEX idx_professions_name ON professions(name);

-- Kategorileri ekle
INSERT INTO categories (id, name, emoji, sort_order) VALUES
    (1, 'Sağlık ve Tıp', '🏥', 1),
    (2, 'Mühendislik ve Teknik', '🏗️', 2),
    (3, 'Bilişim ve Teknoloji', '💻', 3),
    (4, 'Eğitim ve Akademi', '📚', 4),
    (5, 'Hukuk ve Adalet', '⚖️', 5),
    (6, 'İş ve Finans', '💰', 6),
    (7, 'Sanat, Medya ve Eğlence', '🎨', 7),
    (8, 'Sanayi ve Üretim', '🏭', 8),
    (9, 'Tarım ve Hayvancılık', '🌾', 9),
    (10, 'Gıda ve İçecek', '🍽️', 10),
    (11, 'Ulaşım ve Lojistik', '🚚', 11),
    (12, 'Kamu ve Yönetim', '🏛️', 12),
    (13, 'Perakende ve Satış', '🛍️', 13),
    (14, 'İnşaat ve Yapı', '🏗️', 14),
    (15, 'Hizmet ve Bakım', '🧹', 15),
    (16, 'Danışmanlık ve Profesyonel Hizmetler', '💼', 16);
INSERT INTO professions (id, name, category_id) VALUES (1, 'Aile hekimi', 1);
INSERT INTO professions (id, name, category_id) VALUES (2, 'Çocuk doktoru', 1);
INSERT INTO professions (id, name, category_id) VALUES (3, 'Göz doktoru', 1);
INSERT INTO professions (id, name, category_id) VALUES (4, 'Ürolog', 1);
INSERT INTO professions (id, name, category_id) VALUES (5, 'Kardiyolog', 1);
INSERT INTO professions (id, name, category_id) VALUES (6, 'Jinekolog', 1);
INSERT INTO professions (id, name, category_id) VALUES (7, 'Nörolog', 1);
INSERT INTO professions (id, name, category_id) VALUES (8, 'Endokrinolog', 1);
INSERT INTO professions (id, name, category_id) VALUES (9, 'Hematolojist', 1);
INSERT INTO professions (id, name, category_id) VALUES (10, 'Göğüs hastalıkları uzmanı', 1);
INSERT INTO professions (id, name, category_id) VALUES (11, 'Patolog', 1);
INSERT INTO professions (id, name, category_id) VALUES (12, 'Radyolog', 1);
INSERT INTO professions (id, name, category_id) VALUES (13, 'Psikiyatr', 1);
INSERT INTO professions (id, name, category_id) VALUES (14, 'Dermatolog', 1);
INSERT INTO professions (id, name, category_id) VALUES (15, 'Ortopedist', 1);
INSERT INTO professions (id, name, category_id) VALUES (16, 'Fizik tedavi uzmanı', 1);
INSERT INTO professions (id, name, category_id) VALUES (17, 'Cerrah', 1);
INSERT INTO professions (id, name, category_id) VALUES (18, 'Anestezi uzmanı', 1);
INSERT INTO professions (id, name, category_id) VALUES (19, 'Diş hekimi', 1);
INSERT INTO professions (id, name, category_id) VALUES (20, 'Diş teknisyeni', 1);
INSERT INTO professions (id, name, category_id) VALUES (21, 'Veteriner hekim', 1);
INSERT INTO professions (id, name, category_id) VALUES (22, 'Veteriner sağlık teknisyeni', 1);
INSERT INTO professions (id, name, category_id) VALUES (23, 'Hemşire', 1);
INSERT INTO professions (id, name, category_id) VALUES (24, 'Ebe', 1);
INSERT INTO professions (id, name, category_id) VALUES (25, 'Acil tıp teknisyeni', 1);
INSERT INTO professions (id, name, category_id) VALUES (26, 'Paramedik', 1);
INSERT INTO professions (id, name, category_id) VALUES (27, 'Anestezi teknikeri', 1);
INSERT INTO professions (id, name, category_id) VALUES (28, 'Radyoloji teknisyeni', 1);
INSERT INTO professions (id, name, category_id) VALUES (29, 'Laborant', 1);
INSERT INTO professions (id, name, category_id) VALUES (30, 'Dil ve Konuşma Terapisti', 1);
INSERT INTO professions (id, name, category_id) VALUES (31, 'Fizyoterapist', 1);
INSERT INTO professions (id, name, category_id) VALUES (32, 'İş ve Uğraşı Terapisti', 1);
INSERT INTO professions (id, name, category_id) VALUES (33, 'Odyolog', 1);
INSERT INTO professions (id, name, category_id) VALUES (34, 'Diyetisyen', 1);
INSERT INTO professions (id, name, category_id) VALUES (35, 'Optometrist', 1);
INSERT INTO professions (id, name, category_id) VALUES (36, 'Psikolog', 1);
INSERT INTO professions (id, name, category_id) VALUES (37, 'Psikolojik danışman', 1);
INSERT INTO professions (id, name, category_id) VALUES (38, 'İç Hastalıkları Uzmanı', 1);
INSERT INTO professions (id, name, category_id) VALUES (39, 'Enfeksiyon Hastalıkları Uzmanı', 1);
INSERT INTO professions (id, name, category_id) VALUES (40, 'Onkolog', 1);
INSERT INTO professions (id, name, category_id) VALUES (41, 'Spor Hekimi', 1);
INSERT INTO professions (id, name, category_id) VALUES (42, 'Nükleer Tıp Uzmanı', 1);
INSERT INTO professions (id, name, category_id) VALUES (43, 'Adli Tıp Uzmanı', 1);
INSERT INTO professions (id, name, category_id) VALUES (44, 'Genetik Uzmanı', 1);
INSERT INTO professions (id, name, category_id) VALUES (45, 'Halk Sağlığı Uzmanı', 1);
INSERT INTO professions (id, name, category_id) VALUES (46, 'Acil Tıp Uzmanı', 1);
INSERT INTO professions (id, name, category_id) VALUES (47, 'Beyin Cerrahı', 1);
INSERT INTO professions (id, name, category_id) VALUES (48, 'Kalp ve Damar Cerrahı', 1);
INSERT INTO professions (id, name, category_id) VALUES (49, 'Plastik Cerrah', 1);
INSERT INTO professions (id, name, category_id) VALUES (50, 'Çocuk Cerrahı', 1);
INSERT INTO professions (id, name, category_id) VALUES (51, 'Eczacı', 1);
INSERT INTO professions (id, name, category_id) VALUES (52, 'Eczane Teknisyeni', 1);
INSERT INTO professions (id, name, category_id) VALUES (53, 'Biyomedikal Mühendisi', 1);
INSERT INTO professions (id, name, category_id) VALUES (54, 'Perfüzyonist', 1);
INSERT INTO professions (id, name, category_id) VALUES (55, 'Ameliyathane Teknikeri', 1);
INSERT INTO professions (id, name, category_id) VALUES (56, 'Podolog', 1);
INSERT INTO professions (id, name, category_id) VALUES (57, 'Sağlık Yöneticisi', 1);
INSERT INTO professions (id, name, category_id) VALUES (58, 'Tıbbi Sekreter', 1);
INSERT INTO professions (id, name, category_id) VALUES (59, 'Evde Bakım Hemşiresi', 1);
INSERT INTO professions (id, name, category_id) VALUES (60, 'İnşaat mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (61, 'Makine mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (62, 'Elektrik mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (63, 'Elektronik mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (64, 'Bilgisayar mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (65, 'Yazılım mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (66, 'Kimya mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (67, 'Gıda mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (68, 'Çevre mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (69, 'Endüstri mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (70, 'Endüstri sistemleri mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (71, 'İşletme mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (72, 'Harita mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (73, 'Jeoloji mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (74, 'Jeofizik mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (75, 'Metalurji mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (76, 'Maden mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (77, 'Havacılık ve Uzay mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (78, 'Uzay mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (79, 'Biyomedikal Mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (80, 'Nanoteknoloji mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (81, 'Genetik mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (82, 'Elektrik-Elektronik mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (83, 'Elektronik ve Haberleşme mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (84, 'İç mimar', 2);
INSERT INTO professions (id, name, category_id) VALUES (85, 'Peyzaj mimarı', 2);
INSERT INTO professions (id, name, category_id) VALUES (86, 'Mimar', 2);
INSERT INTO professions (id, name, category_id) VALUES (87, 'Tekniker', 2);
INSERT INTO professions (id, name, category_id) VALUES (88, 'Teknisyen', 2);
INSERT INTO professions (id, name, category_id) VALUES (89, 'Test mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (90, 'Kalite kontrol mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (91, 'Sistem mühendisi', 2);
INSERT INTO professions (id, name, category_id) VALUES (92, 'Bilgisayar programcısı', 3);
INSERT INTO professions (id, name, category_id) VALUES (93, 'Yazılım geliştirici', 3);
INSERT INTO professions (id, name, category_id) VALUES (94, 'Veri bilimcisi / analisti', 3);
INSERT INTO professions (id, name, category_id) VALUES (95, 'Veritabanı yöneticisi', 3);
INSERT INTO professions (id, name, category_id) VALUES (96, 'Sistem yöneticisi', 3);
INSERT INTO professions (id, name, category_id) VALUES (97, 'Ağ yöneticisi', 3);
INSERT INTO professions (id, name, category_id) VALUES (98, 'Siber güvenlik uzmanı', 3);
INSERT INTO professions (id, name, category_id) VALUES (99, 'Yapay zeka uzmanı', 3);
INSERT INTO professions (id, name, category_id) VALUES (100, 'UX tasarımcısı', 3);
INSERT INTO professions (id, name, category_id) VALUES (101, 'Web geliştirici', 3);
INSERT INTO professions (id, name, category_id) VALUES (102, 'Mobil uygulama geliştirici', 3);
INSERT INTO professions (id, name, category_id) VALUES (103, 'Bilgi işlemci', 3);
INSERT INTO professions (id, name, category_id) VALUES (104, 'Veri hazırlama ve kontrol işletmeni', 3);
INSERT INTO professions (id, name, category_id) VALUES (105, 'Uydu antenci', 3);
INSERT INTO professions (id, name, category_id) VALUES (106, 'Telefon operatörü', 3);
INSERT INTO professions (id, name, category_id) VALUES (107, 'Bilgisayar tamircisi', 3);
INSERT INTO professions (id, name, category_id) VALUES (108, 'Telekomünikasyon uzmanı', 3);
INSERT INTO professions (id, name, category_id) VALUES (109, 'IT danışmanı', 3);
INSERT INTO professions (id, name, category_id) VALUES (110, 'Bulut mimarı', 3);
INSERT INTO professions (id, name, category_id) VALUES (111, 'DevOps mühendisi', 3);
INSERT INTO professions (id, name, category_id) VALUES (112, 'Öğretmen', 4);
INSERT INTO professions (id, name, category_id) VALUES (113, 'Akademisyen', 4);
INSERT INTO professions (id, name, category_id) VALUES (114, 'Profesör', 4);
INSERT INTO professions (id, name, category_id) VALUES (115, 'Okutman', 4);
INSERT INTO professions (id, name, category_id) VALUES (116, 'Araştırmacı', 4);
INSERT INTO professions (id, name, category_id) VALUES (117, 'Bilim insanı', 4);
INSERT INTO professions (id, name, category_id) VALUES (118, 'Eğitimci', 4);
INSERT INTO professions (id, name, category_id) VALUES (119, 'Eğitmen', 4);
INSERT INTO professions (id, name, category_id) VALUES (120, 'Okul müdürü', 4);
INSERT INTO professions (id, name, category_id) VALUES (121, 'Rehber öğretmen', 4);
INSERT INTO professions (id, name, category_id) VALUES (122, 'Özel eğitim öğretmeni', 4);
INSERT INTO professions (id, name, category_id) VALUES (123, 'Kütüphaneci', 4);
INSERT INTO professions (id, name, category_id) VALUES (124, 'Arşivci', 4);
INSERT INTO professions (id, name, category_id) VALUES (125, 'Antropolog', 4);
INSERT INTO professions (id, name, category_id) VALUES (126, 'Sosyolog', 4);
INSERT INTO professions (id, name, category_id) VALUES (127, 'Psikolog', 4);
INSERT INTO professions (id, name, category_id) VALUES (128, 'Filozof', 4);
INSERT INTO professions (id, name, category_id) VALUES (129, 'Tarihçi', 4);
INSERT INTO professions (id, name, category_id) VALUES (130, 'Coğrafyacı', 4);
INSERT INTO professions (id, name, category_id) VALUES (131, 'Matematikçi', 4);
INSERT INTO professions (id, name, category_id) VALUES (132, 'Fizikçi', 4);
INSERT INTO professions (id, name, category_id) VALUES (133, 'Kimyager', 4);
INSERT INTO professions (id, name, category_id) VALUES (134, 'Biyolog', 4);
INSERT INTO professions (id, name, category_id) VALUES (135, 'Astronom', 4);
INSERT INTO professions (id, name, category_id) VALUES (136, 'Astrofizikçi', 4);
INSERT INTO professions (id, name, category_id) VALUES (137, 'Jeolog', 4);
INSERT INTO professions (id, name, category_id) VALUES (138, 'Meteoroloji uzmanı', 4);
INSERT INTO professions (id, name, category_id) VALUES (139, 'Klimatolog', 4);
INSERT INTO professions (id, name, category_id) VALUES (140, 'Botanikçi', 4);
INSERT INTO professions (id, name, category_id) VALUES (141, 'Zoolog', 4);
INSERT INTO professions (id, name, category_id) VALUES (142, 'Mikrobiyolog', 4);
INSERT INTO professions (id, name, category_id) VALUES (143, 'Genetikçi', 4);
INSERT INTO professions (id, name, category_id) VALUES (144, 'Etimolog', 4);
INSERT INTO professions (id, name, category_id) VALUES (145, 'Etnolog', 4);
INSERT INTO professions (id, name, category_id) VALUES (146, 'Etolojist', 4);
INSERT INTO professions (id, name, category_id) VALUES (147, 'Arkeolog', 4);
INSERT INTO professions (id, name, category_id) VALUES (148, 'Halkbilimci', 4);
INSERT INTO professions (id, name, category_id) VALUES (149, 'Edebiyatçı', 4);
INSERT INTO professions (id, name, category_id) VALUES (150, 'Dilci', 4);
INSERT INTO professions (id, name, category_id) VALUES (151, 'Gramer uzmanı', 4);
INSERT INTO professions (id, name, category_id) VALUES (152, 'Avukat', 5);
INSERT INTO professions (id, name, category_id) VALUES (153, 'Hakim', 5);
INSERT INTO professions (id, name, category_id) VALUES (154, 'Savcı', 5);
INSERT INTO professions (id, name, category_id) VALUES (155, 'Arabulucu', 5);
INSERT INTO professions (id, name, category_id) VALUES (156, 'Noter', 5);
INSERT INTO professions (id, name, category_id) VALUES (157, 'Hukukçu', 5);
INSERT INTO professions (id, name, category_id) VALUES (158, 'Adli tabip', 5);
INSERT INTO professions (id, name, category_id) VALUES (159, 'Adli tıp uzmanı', 5);
INSERT INTO professions (id, name, category_id) VALUES (160, 'İcra memuru', 5);
INSERT INTO professions (id, name, category_id) VALUES (161, 'Sorgu hâkimi', 5);
INSERT INTO professions (id, name, category_id) VALUES (162, 'Sulh hâkimi', 5);
INSERT INTO professions (id, name, category_id) VALUES (163, 'Yargıç', 5);
INSERT INTO professions (id, name, category_id) VALUES (164, 'Bilirkişi', 5);
INSERT INTO professions (id, name, category_id) VALUES (165, 'Hukuk danışmanı', 5);
INSERT INTO professions (id, name, category_id) VALUES (166, 'İnsan hakları uzmanı', 5);
INSERT INTO professions (id, name, category_id) VALUES (167, 'Vergi müfettişi', 5);
INSERT INTO professions (id, name, category_id) VALUES (168, 'Vergi denetmeni', 5);
INSERT INTO professions (id, name, category_id) VALUES (169, 'Bankacı', 6);
INSERT INTO professions (id, name, category_id) VALUES (170, 'Banker', 6);
INSERT INTO professions (id, name, category_id) VALUES (171, 'Finansör', 6);
INSERT INTO professions (id, name, category_id) VALUES (172, 'Borsacı', 6);
INSERT INTO professions (id, name, category_id) VALUES (173, 'Sigortacı', 6);
INSERT INTO professions (id, name, category_id) VALUES (174, 'Muhasebeci', 6);
INSERT INTO professions (id, name, category_id) VALUES (175, 'Serbest muhasebeci mali müşavir', 6);
INSERT INTO professions (id, name, category_id) VALUES (176, 'Yeminli mali müşavir', 6);
INSERT INTO professions (id, name, category_id) VALUES (177, 'Ekonomist', 6);
INSERT INTO professions (id, name, category_id) VALUES (178, 'İktisatçı', 6);
INSERT INTO professions (id, name, category_id) VALUES (179, 'Mali hizmetler uzmanı', 6);
INSERT INTO professions (id, name, category_id) VALUES (180, 'Gelir uzmanı', 6);
INSERT INTO professions (id, name, category_id) VALUES (181, 'Gelir uzman yardımcısı', 6);
INSERT INTO professions (id, name, category_id) VALUES (182, 'Bütçe uzmanı', 6);
INSERT INTO professions (id, name, category_id) VALUES (183, 'Fon yöneticisi', 6);
INSERT INTO professions (id, name, category_id) VALUES (184, 'Yatırım uzmanı', 6);
INSERT INTO professions (id, name, category_id) VALUES (185, 'Portföy yöneticisi', 6);
INSERT INTO professions (id, name, category_id) VALUES (186, 'Risk analisti', 6);
INSERT INTO professions (id, name, category_id) VALUES (187, 'Vergi danışmanı', 6);
INSERT INTO professions (id, name, category_id) VALUES (188, 'Denetçi', 6);
INSERT INTO professions (id, name, category_id) VALUES (189, 'İç denetçi', 6);
INSERT INTO professions (id, name, category_id) VALUES (190, 'Mali müşavir', 6);
INSERT INTO professions (id, name, category_id) VALUES (191, 'Broker', 6);
INSERT INTO professions (id, name, category_id) VALUES (192, 'Dövizci', 6);
INSERT INTO professions (id, name, category_id) VALUES (193, 'Sarraf', 6);
INSERT INTO professions (id, name, category_id) VALUES (194, 'Ressam', 7);
INSERT INTO professions (id, name, category_id) VALUES (195, 'Heykeltıraş', 7);
INSERT INTO professions (id, name, category_id) VALUES (196, 'Müzisyen', 7);
INSERT INTO professions (id, name, category_id) VALUES (197, 'Şarkıcı', 7);
INSERT INTO professions (id, name, category_id) VALUES (198, 'Besteci', 7);
INSERT INTO professions (id, name, category_id) VALUES (199, 'Şarkı sözü yazarı', 7);
INSERT INTO professions (id, name, category_id) VALUES (200, 'Dansçı', 7);
INSERT INTO professions (id, name, category_id) VALUES (201, 'Koreograf', 7);
INSERT INTO professions (id, name, category_id) VALUES (202, 'Oyuncu', 7);
INSERT INTO professions (id, name, category_id) VALUES (203, 'Aktör', 7);
INSERT INTO professions (id, name, category_id) VALUES (204, 'Aktris', 7);
INSERT INTO professions (id, name, category_id) VALUES (205, 'Film yönetmeni', 7);
INSERT INTO professions (id, name, category_id) VALUES (206, 'Tiyatro yönetmeni', 7);
INSERT INTO professions (id, name, category_id) VALUES (207, 'Senarist', 7);
INSERT INTO professions (id, name, category_id) VALUES (208, 'Yazar', 7);
INSERT INTO professions (id, name, category_id) VALUES (209, 'Şair', 7);
INSERT INTO professions (id, name, category_id) VALUES (210, 'Gazeteci', 7);
INSERT INTO professions (id, name, category_id) VALUES (211, 'Muhabir', 7);
INSERT INTO professions (id, name, category_id) VALUES (212, 'Radyocu', 7);
INSERT INTO professions (id, name, category_id) VALUES (213, 'Spiker', 7);
INSERT INTO professions (id, name, category_id) VALUES (214, 'Sunucu', 7);
INSERT INTO professions (id, name, category_id) VALUES (215, 'Fotoğrafçı', 7);
INSERT INTO professions (id, name, category_id) VALUES (216, 'Kameraman', 7);
INSERT INTO professions (id, name, category_id) VALUES (217, 'Video editörü', 7);
INSERT INTO professions (id, name, category_id) VALUES (218, 'Ses teknisyeni', 7);
INSERT INTO professions (id, name, category_id) VALUES (219, 'Grafik tasarımcısı', 7);
INSERT INTO professions (id, name, category_id) VALUES (220, 'İllüstratör', 7);
INSERT INTO professions (id, name, category_id) VALUES (221, 'Animatör', 7);
INSERT INTO professions (id, name, category_id) VALUES (222, 'Karikatürist', 7);
INSERT INTO professions (id, name, category_id) VALUES (223, 'Modacı', 7);
INSERT INTO professions (id, name, category_id) VALUES (224, 'Stilist', 7);
INSERT INTO professions (id, name, category_id) VALUES (225, 'Manken', 7);
INSERT INTO professions (id, name, category_id) VALUES (226, 'Sanat yönetmeni', 7);
INSERT INTO professions (id, name, category_id) VALUES (227, 'İçerik üretici', 7);
INSERT INTO professions (id, name, category_id) VALUES (228, 'Influencer', 7);
INSERT INTO professions (id, name, category_id) VALUES (229, 'Youtuber', 7);
INSERT INTO professions (id, name, category_id) VALUES (230, 'Prodüktör', 7);
INSERT INTO professions (id, name, category_id) VALUES (231, 'Yapımcı', 7);
INSERT INTO professions (id, name, category_id) VALUES (232, 'Casting direktörü', 7);
INSERT INTO professions (id, name, category_id) VALUES (233, 'Sahne tasarımcısı', 7);
INSERT INTO professions (id, name, category_id) VALUES (234, 'Kostüm tasarımcısı', 7);
INSERT INTO professions (id, name, category_id) VALUES (235, 'Makyaj sanatçısı', 7);
INSERT INTO professions (id, name, category_id) VALUES (236, 'Kuaför', 7);
INSERT INTO professions (id, name, category_id) VALUES (237, 'Manikürcü', 7);
INSERT INTO professions (id, name, category_id) VALUES (238, 'Estetisyen', 7);
INSERT INTO professions (id, name, category_id) VALUES (239, 'Masör', 7);
INSERT INTO professions (id, name, category_id) VALUES (240, 'Masöz', 7);
INSERT INTO professions (id, name, category_id) VALUES (241, 'Fabrika işçisi', 8);
INSERT INTO professions (id, name, category_id) VALUES (242, 'Makinist', 8);
INSERT INTO professions (id, name, category_id) VALUES (243, 'Kalıpçı', 8);
INSERT INTO professions (id, name, category_id) VALUES (244, 'Tornacı', 8);
INSERT INTO professions (id, name, category_id) VALUES (245, 'Kaynakçı', 8);
INSERT INTO professions (id, name, category_id) VALUES (246, 'Dökümcü', 8);
INSERT INTO professions (id, name, category_id) VALUES (247, 'Demirci', 8);
INSERT INTO professions (id, name, category_id) VALUES (248, 'Marangoz', 8);
INSERT INTO professions (id, name, category_id) VALUES (249, 'Mobilyacı', 8);
INSERT INTO professions (id, name, category_id) VALUES (250, 'Kalaycı', 8);
INSERT INTO professions (id, name, category_id) VALUES (251, 'Bakırcı', 8);
INSERT INTO professions (id, name, category_id) VALUES (252, 'Terzi', 8);
INSERT INTO professions (id, name, category_id) VALUES (253, 'Dokumacı', 8);
INSERT INTO professions (id, name, category_id) VALUES (254, 'İplikçi', 8);
INSERT INTO professions (id, name, category_id) VALUES (255, 'Çorapçı', 8);
INSERT INTO professions (id, name, category_id) VALUES (256, 'Halıcı', 8);
INSERT INTO professions (id, name, category_id) VALUES (257, 'Kumaşçı', 8);
INSERT INTO professions (id, name, category_id) VALUES (258, 'Derici', 8);
INSERT INTO professions (id, name, category_id) VALUES (259, 'Ayakkabıcı', 8);
INSERT INTO professions (id, name, category_id) VALUES (260, 'Çanta imalatçısı', 8);
INSERT INTO professions (id, name, category_id) VALUES (261, 'Camcı', 8);
INSERT INTO professions (id, name, category_id) VALUES (262, 'Seramikçi', 8);
INSERT INTO professions (id, name, category_id) VALUES (263, 'Çinicisi', 8);
INSERT INTO professions (id, name, category_id) VALUES (264, 'Mermerci', 8);
INSERT INTO professions (id, name, category_id) VALUES (265, 'Taşçı', 8);
INSERT INTO professions (id, name, category_id) VALUES (266, 'Boyacı', 8);
INSERT INTO professions (id, name, category_id) VALUES (267, 'Badanacı', 8);
INSERT INTO professions (id, name, category_id) VALUES (268, 'Zımparacı', 8);
INSERT INTO professions (id, name, category_id) VALUES (269, 'Polisajcı', 8);
INSERT INTO professions (id, name, category_id) VALUES (270, 'Kaportacı', 8);
INSERT INTO professions (id, name, category_id) VALUES (271, 'Karoserci', 8);
INSERT INTO professions (id, name, category_id) VALUES (272, 'Oto tamircisi', 8);
INSERT INTO professions (id, name, category_id) VALUES (273, 'Oto elektrikçisi', 8);
INSERT INTO professions (id, name, category_id) VALUES (274, 'Motor tamircisi', 8);
INSERT INTO professions (id, name, category_id) VALUES (275, 'Bisiklet tamircisi', 8);
INSERT INTO professions (id, name, category_id) VALUES (276, 'Saat tamircisi', 8);
INSERT INTO professions (id, name, category_id) VALUES (277, 'Bujici', 8);
INSERT INTO professions (id, name, category_id) VALUES (278, 'Bobinajcı', 8);
INSERT INTO professions (id, name, category_id) VALUES (279, 'Matkapçı', 8);
INSERT INTO professions (id, name, category_id) VALUES (280, 'Vinç operatörü', 8);
INSERT INTO professions (id, name, category_id) VALUES (281, 'Forklift operatörü', 8);
INSERT INTO professions (id, name, category_id) VALUES (282, 'Buldozer operatörü', 8);
INSERT INTO professions (id, name, category_id) VALUES (283, 'Greyder operatörü', 8);
INSERT INTO professions (id, name, category_id) VALUES (284, 'Silindir operatörü', 8);
INSERT INTO professions (id, name, category_id) VALUES (285, 'Konveyör operatörü', 8);
INSERT INTO professions (id, name, category_id) VALUES (286, 'İstihkâmcı', 8);
INSERT INTO professions (id, name, category_id) VALUES (287, 'İtfaiyeci', 8);
INSERT INTO professions (id, name, category_id) VALUES (288, 'Çiftçi', 9);
INSERT INTO professions (id, name, category_id) VALUES (289, 'Ziraat mühendisi', 9);
INSERT INTO professions (id, name, category_id) VALUES (290, 'Bahçıvan', 9);
INSERT INTO professions (id, name, category_id) VALUES (291, 'Peyzaj teknikeri', 9);
INSERT INTO professions (id, name, category_id) VALUES (292, 'Orman mühendisi', 9);
INSERT INTO professions (id, name, category_id) VALUES (293, 'Arıcı', 9);
INSERT INTO professions (id, name, category_id) VALUES (294, 'Balıkçı', 9);
INSERT INTO professions (id, name, category_id) VALUES (295, 'Tavukçu', 9);
INSERT INTO professions (id, name, category_id) VALUES (296, 'Besici', 9);
INSERT INTO professions (id, name, category_id) VALUES (297, 'Çoban', 9);
INSERT INTO professions (id, name, category_id) VALUES (298, 'Seyis', 9);
INSERT INTO professions (id, name, category_id) VALUES (299, 'Hayvan bakıcısı', 9);
INSERT INTO professions (id, name, category_id) VALUES (300, 'Hayvan terbiyecisi', 9);
INSERT INTO professions (id, name, category_id) VALUES (301, 'Veteriner', 9);
INSERT INTO professions (id, name, category_id) VALUES (302, 'Tarım işçisi', 9);
INSERT INTO professions (id, name, category_id) VALUES (303, 'Bahçe bitkileri uzmanı', 9);
INSERT INTO professions (id, name, category_id) VALUES (304, 'Peyzaj mimarı', 9);
INSERT INTO professions (id, name, category_id) VALUES (305, 'Sera işletmecisi', 9);
INSERT INTO professions (id, name, category_id) VALUES (306, 'Zirai ilaç uzmanı', 9);
INSERT INTO professions (id, name, category_id) VALUES (307, 'Tarım makineleri operatörü', 9);
INSERT INTO professions (id, name, category_id) VALUES (308, 'Ormancı', 9);
INSERT INTO professions (id, name, category_id) VALUES (309, 'Ağaç kesici', 9);
INSERT INTO professions (id, name, category_id) VALUES (310, 'Fidan yetiştiricisi', 9);
INSERT INTO professions (id, name, category_id) VALUES (311, 'Aşçı', 10);
INSERT INTO professions (id, name, category_id) VALUES (312, 'Aşçıbaşı', 10);
INSERT INTO professions (id, name, category_id) VALUES (313, 'Fırıncı', 10);
INSERT INTO professions (id, name, category_id) VALUES (314, 'Pastacı', 10);
INSERT INTO professions (id, name, category_id) VALUES (315, 'Tatlıcı', 10);
INSERT INTO professions (id, name, category_id) VALUES (316, 'Börekçi', 10);
INSERT INTO professions (id, name, category_id) VALUES (317, 'Pideci', 10);
INSERT INTO professions (id, name, category_id) VALUES (318, 'Lahmacuncu', 10);
INSERT INTO professions (id, name, category_id) VALUES (319, 'Kebapçı', 10);
INSERT INTO professions (id, name, category_id) VALUES (320, 'Köfteci', 10);
INSERT INTO professions (id, name, category_id) VALUES (321, 'Pilavcı', 10);
INSERT INTO professions (id, name, category_id) VALUES (322, 'Mantarcı', 10);
INSERT INTO professions (id, name, category_id) VALUES (323, 'Çikolatacı', 10);
INSERT INTO professions (id, name, category_id) VALUES (324, 'Dondurmacı', 10);
INSERT INTO professions (id, name, category_id) VALUES (325, 'Yoğurtçu', 10);
INSERT INTO professions (id, name, category_id) VALUES (326, 'Sütçü', 10);
INSERT INTO professions (id, name, category_id) VALUES (327, 'Peynirci', 10);
INSERT INTO professions (id, name, category_id) VALUES (328, 'Turşucu', 10);
INSERT INTO professions (id, name, category_id) VALUES (329, 'Tuzcu', 10);
INSERT INTO professions (id, name, category_id) VALUES (330, 'Zeytinci', 10);
INSERT INTO professions (id, name, category_id) VALUES (331, 'Şarap üreticisi', 10);
INSERT INTO professions (id, name, category_id) VALUES (332, 'Biracı', 10);
INSERT INTO professions (id, name, category_id) VALUES (333, 'Barmen', 10);
INSERT INTO professions (id, name, category_id) VALUES (334, 'Barista', 10);
INSERT INTO professions (id, name, category_id) VALUES (335, 'Garson', 10);
INSERT INTO professions (id, name, category_id) VALUES (336, 'Komi', 10);
INSERT INTO professions (id, name, category_id) VALUES (337, 'Lokantacı', 10);
INSERT INTO professions (id, name, category_id) VALUES (338, 'Kahveci', 10);
INSERT INTO professions (id, name, category_id) VALUES (339, 'Çaycı', 10);
INSERT INTO professions (id, name, category_id) VALUES (340, 'Meyhaneci', 10);
INSERT INTO professions (id, name, category_id) VALUES (341, 'Salepçi', 10);
INSERT INTO professions (id, name, category_id) VALUES (342, 'Simitçi', 10);
INSERT INTO professions (id, name, category_id) VALUES (343, 'Un fabrikası işçisi', 10);
INSERT INTO professions (id, name, category_id) VALUES (344, 'Et işleme uzmanı', 10);
INSERT INTO professions (id, name, category_id) VALUES (345, 'Kasap', 10);
INSERT INTO professions (id, name, category_id) VALUES (346, 'Balıkçı', 10);
INSERT INTO professions (id, name, category_id) VALUES (347, 'Deniz ürünleri işleyici', 10);
INSERT INTO professions (id, name, category_id) VALUES (348, 'Gıda mühendisi', 10);
INSERT INTO professions (id, name, category_id) VALUES (349, 'Gıda teknisyeni', 10);
INSERT INTO professions (id, name, category_id) VALUES (350, 'Pastörizr', 10);
INSERT INTO professions (id, name, category_id) VALUES (351, 'Fermentasyon işçisi', 10);
INSERT INTO professions (id, name, category_id) VALUES (352, 'Pilot', 11);
INSERT INTO professions (id, name, category_id) VALUES (353, 'Uçuş teknisyeni', 11);
INSERT INTO professions (id, name, category_id) VALUES (354, 'Hostes', 11);
INSERT INTO professions (id, name, category_id) VALUES (355, 'Kabin görevlisi', 11);
INSERT INTO professions (id, name, category_id) VALUES (356, 'Kaptan', 11);
INSERT INTO professions (id, name, category_id) VALUES (357, 'Gemici', 11);
INSERT INTO professions (id, name, category_id) VALUES (358, 'Denizci', 11);
INSERT INTO professions (id, name, category_id) VALUES (359, 'Tren makinisti', 11);
INSERT INTO professions (id, name, category_id) VALUES (360, 'Vatman', 11);
INSERT INTO professions (id, name, category_id) VALUES (361, 'Şoför', 11);
INSERT INTO professions (id, name, category_id) VALUES (362, 'Taksici', 11);
INSERT INTO professions (id, name, category_id) VALUES (363, 'Kamyoncu', 11);
INSERT INTO professions (id, name, category_id) VALUES (364, 'Kurye', 11);
INSERT INTO professions (id, name, category_id) VALUES (365, 'Nakliyeci', 11);
INSERT INTO professions (id, name, category_id) VALUES (366, 'Ambulans şoförü', 11);
INSERT INTO professions (id, name, category_id) VALUES (367, 'Özel şoför', 11);
INSERT INTO professions (id, name, category_id) VALUES (368, 'Forklift operatörü', 11);
INSERT INTO professions (id, name, category_id) VALUES (369, 'Vinç operatörü', 11);
INSERT INTO professions (id, name, category_id) VALUES (370, 'Liman işçisi', 11);
INSERT INTO professions (id, name, category_id) VALUES (371, 'Gümrük memuru', 11);
INSERT INTO professions (id, name, category_id) VALUES (372, 'Gümrük müşaviri', 11);
INSERT INTO professions (id, name, category_id) VALUES (373, 'Gümrük uzmanı', 11);
INSERT INTO professions (id, name, category_id) VALUES (374, 'Lojistik uzmanı', 11);
INSERT INTO professions (id, name, category_id) VALUES (375, 'Depocu', 11);
INSERT INTO professions (id, name, category_id) VALUES (376, 'Sevkiyat sorumlusu', 11);
INSERT INTO professions (id, name, category_id) VALUES (377, 'Ulaşım sorumlusu', 11);
INSERT INTO professions (id, name, category_id) VALUES (378, 'Hava trafik kontrolörü', 11);
INSERT INTO professions (id, name, category_id) VALUES (379, 'Demiryolu işçisi', 11);
INSERT INTO professions (id, name, category_id) VALUES (380, 'Otobüs şoförü', 11);
INSERT INTO professions (id, name, category_id) VALUES (381, 'Minibüs şoförü', 11);
INSERT INTO professions (id, name, category_id) VALUES (382, 'Taksi dolmuş şoförü', 11);
INSERT INTO professions (id, name, category_id) VALUES (383, 'Uçak bakım teknisyeni', 11);
INSERT INTO professions (id, name, category_id) VALUES (384, 'Cumhurbaşkanı', 12);
INSERT INTO professions (id, name, category_id) VALUES (385, 'Başbakan', 12);
INSERT INTO professions (id, name, category_id) VALUES (386, 'Bakan', 12);
INSERT INTO professions (id, name, category_id) VALUES (387, 'Milletvekili', 12);
INSERT INTO professions (id, name, category_id) VALUES (388, 'Belediye başkanı', 12);
INSERT INTO professions (id, name, category_id) VALUES (389, 'Belediye meclisi üyesi', 12);
INSERT INTO professions (id, name, category_id) VALUES (390, 'Vali', 12);
INSERT INTO professions (id, name, category_id) VALUES (391, 'Kaymakam', 12);
INSERT INTO professions (id, name, category_id) VALUES (392, 'Muhtar', 12);
INSERT INTO professions (id, name, category_id) VALUES (393, 'Büyükelçi', 12);
INSERT INTO professions (id, name, category_id) VALUES (394, 'Konsolos', 12);
INSERT INTO professions (id, name, category_id) VALUES (395, 'Diplomat', 12);
INSERT INTO professions (id, name, category_id) VALUES (396, 'Devlet memuru', 12);
INSERT INTO professions (id, name, category_id) VALUES (397, 'Memur', 12);
INSERT INTO professions (id, name, category_id) VALUES (398, 'Müdür', 12);
INSERT INTO professions (id, name, category_id) VALUES (399, 'Genel müdür', 12);
INSERT INTO professions (id, name, category_id) VALUES (400, 'İcra kurulu başkanı', 12);
INSERT INTO professions (id, name, category_id) VALUES (401, 'Yönetici', 12);
INSERT INTO professions (id, name, category_id) VALUES (402, 'İşletmeci', 12);
INSERT INTO professions (id, name, category_id) VALUES (403, 'Müteahhit', 12);
INSERT INTO professions (id, name, category_id) VALUES (404, 'Müfettiş', 12);
INSERT INTO professions (id, name, category_id) VALUES (405, 'Denetçi', 12);
INSERT INTO professions (id, name, category_id) VALUES (406, 'Denetleyici', 12);
INSERT INTO professions (id, name, category_id) VALUES (407, 'Kontrolör', 12);
INSERT INTO professions (id, name, category_id) VALUES (408, 'Sicil memuru', 12);
INSERT INTO professions (id, name, category_id) VALUES (409, 'İcra memuru', 12);
INSERT INTO professions (id, name, category_id) VALUES (410, 'Tahsildar', 12);
INSERT INTO professions (id, name, category_id) VALUES (411, 'Veznedar', 12);
INSERT INTO professions (id, name, category_id) VALUES (412, 'Zabıt katibi', 12);
INSERT INTO professions (id, name, category_id) VALUES (413, 'Zabıta memuru', 12);
INSERT INTO professions (id, name, category_id) VALUES (414, 'Emniyet amiri', 12);
INSERT INTO professions (id, name, category_id) VALUES (415, 'Emniyet genel müdürü', 12);
INSERT INTO professions (id, name, category_id) VALUES (416, 'Komiser', 12);
INSERT INTO professions (id, name, category_id) VALUES (417, 'Komiser yardımcısı', 12);
INSERT INTO professions (id, name, category_id) VALUES (418, 'Polis memuru', 12);
INSERT INTO professions (id, name, category_id) VALUES (419, 'Polis şefi', 12);
INSERT INTO professions (id, name, category_id) VALUES (420, 'Jandarma', 12);
INSERT INTO professions (id, name, category_id) VALUES (421, 'Asker', 12);
INSERT INTO professions (id, name, category_id) VALUES (422, 'Subay', 12);
INSERT INTO professions (id, name, category_id) VALUES (423, 'Astsubay', 12);
INSERT INTO professions (id, name, category_id) VALUES (424, 'Teğmen', 12);
INSERT INTO professions (id, name, category_id) VALUES (425, 'Yüzbaşı', 12);
INSERT INTO professions (id, name, category_id) VALUES (426, 'Binbaşı', 12);
INSERT INTO professions (id, name, category_id) VALUES (427, 'Yarbay', 12);
INSERT INTO professions (id, name, category_id) VALUES (428, 'Albay', 12);
INSERT INTO professions (id, name, category_id) VALUES (429, 'Tuğgeneral', 12);
INSERT INTO professions (id, name, category_id) VALUES (430, 'Tümgeneral', 12);
INSERT INTO professions (id, name, category_id) VALUES (431, 'Korgeneral', 12);
INSERT INTO professions (id, name, category_id) VALUES (432, 'Orgeneral', 12);
INSERT INTO professions (id, name, category_id) VALUES (433, 'Amiral', 12);
INSERT INTO professions (id, name, category_id) VALUES (434, 'Koramiral', 12);
INSERT INTO professions (id, name, category_id) VALUES (435, 'Tümamiral', 12);
INSERT INTO professions (id, name, category_id) VALUES (436, 'Savunma uzmanı', 12);
INSERT INTO professions (id, name, category_id) VALUES (437, 'İstihbarat görevlisi', 12);
INSERT INTO professions (id, name, category_id) VALUES (438, 'Satış elemanı', 13);
INSERT INTO professions (id, name, category_id) VALUES (439, 'Mağaza müdürü', 13);
INSERT INTO professions (id, name, category_id) VALUES (440, 'Mağaza sorumlusu', 13);
INSERT INTO professions (id, name, category_id) VALUES (441, 'Tezgahtar', 13);
INSERT INTO professions (id, name, category_id) VALUES (442, 'Kasiyer', 13);
INSERT INTO professions (id, name, category_id) VALUES (443, 'Manav', 13);
INSERT INTO professions (id, name, category_id) VALUES (444, 'Kasap', 13);
INSERT INTO professions (id, name, category_id) VALUES (445, 'Şarküter', 13);
INSERT INTO professions (id, name, category_id) VALUES (446, 'Balıkçı', 13);
INSERT INTO professions (id, name, category_id) VALUES (447, 'Fırıncı', 13);
INSERT INTO professions (id, name, category_id) VALUES (448, 'Pastacı', 13);
INSERT INTO professions (id, name, category_id) VALUES (449, 'Çiçekçi', 13);
INSERT INTO professions (id, name, category_id) VALUES (450, 'Kitapçı', 13);
INSERT INTO professions (id, name, category_id) VALUES (451, 'Kırtasiyeci', 13);
INSERT INTO professions (id, name, category_id) VALUES (452, 'Züccaciye satıcısı', 13);
INSERT INTO professions (id, name, category_id) VALUES (453, 'Mobilyacı', 13);
INSERT INTO professions (id, name, category_id) VALUES (454, 'Beyaz eşya satıcısı', 13);
INSERT INTO professions (id, name, category_id) VALUES (455, 'Elektronik mağaza satıcısı', 13);
INSERT INTO professions (id, name, category_id) VALUES (456, 'Oto yedek parçacı', 13);
INSERT INTO professions (id, name, category_id) VALUES (457, 'Araba satıcısı', 13);
INSERT INTO professions (id, name, category_id) VALUES (458, 'Emlakçı', 13);
INSERT INTO professions (id, name, category_id) VALUES (459, 'Sigorta acentesi', 13);
INSERT INTO professions (id, name, category_id) VALUES (460, 'Seyahat acentesi', 13);
INSERT INTO professions (id, name, category_id) VALUES (461, 'Turizmci', 13);
INSERT INTO professions (id, name, category_id) VALUES (462, 'Rehber', 13);
INSERT INTO professions (id, name, category_id) VALUES (463, 'Acentacı', 13);
INSERT INTO professions (id, name, category_id) VALUES (464, 'Komisyoncu', 13);
INSERT INTO professions (id, name, category_id) VALUES (465, 'Tuhafiyeci', 13);
INSERT INTO professions (id, name, category_id) VALUES (466, 'Manifaturacı', 13);
INSERT INTO professions (id, name, category_id) VALUES (467, 'Kumaşçı', 13);
INSERT INTO professions (id, name, category_id) VALUES (468, 'Halıcı', 13);
INSERT INTO professions (id, name, category_id) VALUES (469, 'Ayakkabı satıcısı', 13);
INSERT INTO professions (id, name, category_id) VALUES (470, 'Giyim mağazası satıcısı', 13);
INSERT INTO professions (id, name, category_id) VALUES (471, 'Kozmetik satıcısı', 13);
INSERT INTO professions (id, name, category_id) VALUES (472, 'Parfümeri satıcısı', 13);
INSERT INTO professions (id, name, category_id) VALUES (473, 'Mücevher satıcısı', 13);
INSERT INTO professions (id, name, category_id) VALUES (474, 'Antika satıcısı', 13);
INSERT INTO professions (id, name, category_id) VALUES (475, 'İkinci el eşya satıcısı', 13);
INSERT INTO professions (id, name, category_id) VALUES (476, 'Bit pazarı satıcısı', 13);
INSERT INTO professions (id, name, category_id) VALUES (477, 'Sokak satıcısı', 13);
INSERT INTO professions (id, name, category_id) VALUES (478, 'Pazar tezgâhtarı', 13);
INSERT INTO professions (id, name, category_id) VALUES (479, 'Online satış uzmanı', 13);
INSERT INTO professions (id, name, category_id) VALUES (480, 'E-ticaret uzmanı', 13);
INSERT INTO professions (id, name, category_id) VALUES (481, 'Pazarlama uzmanı', 13);
INSERT INTO professions (id, name, category_id) VALUES (482, 'Marka yöneticisi', 13);
INSERT INTO professions (id, name, category_id) VALUES (483, 'Ürün yöneticisi', 13);
INSERT INTO professions (id, name, category_id) VALUES (484, 'CRM uzmanı', 13);
INSERT INTO professions (id, name, category_id) VALUES (485, 'İnşaat mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (486, 'Makine mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (487, 'Elektrik mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (488, 'Elektronik mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (489, 'Bilgisayar mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (490, 'Yazılım mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (491, 'Kimya mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (492, 'Gıda mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (493, 'Çevre mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (494, 'Endüstri mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (495, 'Endüstri sistemleri mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (496, 'İşletme mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (497, 'Harita mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (498, 'Jeoloji mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (499, 'Jeofizik mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (500, 'Metalurji mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (501, 'Maden mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (502, 'Havacılık ve Uzay mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (503, 'Uzay mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (504, 'Biyomedikal Mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (505, 'Nanoteknoloji mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (506, 'Genetik mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (507, 'Elektrik-Elektronik mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (508, 'Elektronik ve Haberleşme mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (509, 'İç mimar', 14);
INSERT INTO professions (id, name, category_id) VALUES (510, 'Peyzaj mimarı', 14);
INSERT INTO professions (id, name, category_id) VALUES (511, 'Mimar', 14);
INSERT INTO professions (id, name, category_id) VALUES (512, 'Tekniker', 14);
INSERT INTO professions (id, name, category_id) VALUES (513, 'Teknisyen', 14);
INSERT INTO professions (id, name, category_id) VALUES (514, 'Test mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (515, 'Kalite kontrol mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (516, 'Sistem mühendisi', 14);
INSERT INTO professions (id, name, category_id) VALUES (517, 'Temizlikçi', 15);
INSERT INTO professions (id, name, category_id) VALUES (518, 'Ev hanımı / ev işleri yöneticisi', 15);
INSERT INTO professions (id, name, category_id) VALUES (519, 'Dadı', 15);
INSERT INTO professions (id, name, category_id) VALUES (520, 'Bebek bakıcısı', 15);
INSERT INTO professions (id, name, category_id) VALUES (521, 'Hasta bakıcısı', 15);
INSERT INTO professions (id, name, category_id) VALUES (522, 'Yaşlı bakıcısı', 15);
INSERT INTO professions (id, name, category_id) VALUES (523, 'Engelli bakıcısı', 15);
INSERT INTO professions (id, name, category_id) VALUES (524, 'Ev yardımcısı', 15);
INSERT INTO professions (id, name, category_id) VALUES (525, 'Hizmetçi', 15);
INSERT INTO professions (id, name, category_id) VALUES (526, 'Gündelikçi', 15);
INSERT INTO professions (id, name, category_id) VALUES (527, 'Apartman görevlisi', 15);
INSERT INTO professions (id, name, category_id) VALUES (528, 'Kapıcı', 15);
INSERT INTO professions (id, name, category_id) VALUES (529, 'Site yöneticisi', 15);
INSERT INTO professions (id, name, category_id) VALUES (530, 'Güvenlik görevlisi', 15);
INSERT INTO professions (id, name, category_id) VALUES (531, 'Özel güvenlik', 15);
INSERT INTO professions (id, name, category_id) VALUES (532, 'Bekçi', 15);
INSERT INTO professions (id, name, category_id) VALUES (533, 'Park bekçisi', 15);
INSERT INTO professions (id, name, category_id) VALUES (534, 'Valet', 15);
INSERT INTO professions (id, name, category_id) VALUES (535, 'Vale', 15);
INSERT INTO professions (id, name, category_id) VALUES (536, 'Otopark görevlisi', 15);
INSERT INTO professions (id, name, category_id) VALUES (537, 'Otopark yöneticisi', 15);
INSERT INTO professions (id, name, category_id) VALUES (538, 'Otel görevlisi', 15);
INSERT INTO professions (id, name, category_id) VALUES (539, 'Kat görevlisi', 15);
INSERT INTO professions (id, name, category_id) VALUES (540, 'Oda görevlisi', 15);
INSERT INTO professions (id, name, category_id) VALUES (541, 'Resepsiyon memuru', 15);
INSERT INTO professions (id, name, category_id) VALUES (542, 'Ön büro elemanı', 15);
INSERT INTO professions (id, name, category_id) VALUES (543, 'Bellboy', 15);
INSERT INTO professions (id, name, category_id) VALUES (544, 'Komi', 15);
INSERT INTO professions (id, name, category_id) VALUES (545, 'Bulaşıkçı', 15);
INSERT INTO professions (id, name, category_id) VALUES (546, 'Garson', 15);
INSERT INTO professions (id, name, category_id) VALUES (547, 'Barista', 15);
INSERT INTO professions (id, name, category_id) VALUES (548, 'Şef garson', 15);
INSERT INTO professions (id, name, category_id) VALUES (549, 'Restoran müdürü', 15);
INSERT INTO professions (id, name, category_id) VALUES (550, 'Otel müdürü', 15);
INSERT INTO professions (id, name, category_id) VALUES (551, 'Tur rehberi', 15);
INSERT INTO professions (id, name, category_id) VALUES (552, 'Seyahat acentesi çalışanı', 15);
INSERT INTO professions (id, name, category_id) VALUES (553, 'Spa terapisti', 15);
INSERT INTO professions (id, name, category_id) VALUES (554, 'Masör', 15);
INSERT INTO professions (id, name, category_id) VALUES (555, 'Masöz', 15);
INSERT INTO professions (id, name, category_id) VALUES (556, 'Güzellik uzmanı', 15);
INSERT INTO professions (id, name, category_id) VALUES (557, 'Estetisyen', 15);
INSERT INTO professions (id, name, category_id) VALUES (558, 'Manikürcü', 15);
INSERT INTO professions (id, name, category_id) VALUES (559, 'Pedikürcü', 15);
INSERT INTO professions (id, name, category_id) VALUES (560, 'Kuaför', 15);
INSERT INTO professions (id, name, category_id) VALUES (561, 'Berber', 15);
INSERT INTO professions (id, name, category_id) VALUES (562, 'Tıraşçı', 15);
INSERT INTO professions (id, name, category_id) VALUES (563, 'Sakal uzmanı', 15);
INSERT INTO professions (id, name, category_id) VALUES (564, 'Dövme sanatçısı', 15);
INSERT INTO professions (id, name, category_id) VALUES (565, 'Piercing uzmanı', 15);
INSERT INTO professions (id, name, category_id) VALUES (566, 'Solaryum uzmanı', 15);
INSERT INTO professions (id, name, category_id) VALUES (567, 'SPA yöneticisi', 15);
INSERT INTO professions (id, name, category_id) VALUES (568, 'Fitness eğitmeni', 15);
INSERT INTO professions (id, name, category_id) VALUES (569, 'Yoga eğitmeni', 15);
INSERT INTO professions (id, name, category_id) VALUES (570, 'Pilates eğitmeni', 15);
INSERT INTO professions (id, name, category_id) VALUES (571, 'Dans eğitmeni', 15);
INSERT INTO professions (id, name, category_id) VALUES (572, 'Yüzme eğitmeni', 15);
INSERT INTO professions (id, name, category_id) VALUES (573, 'Spor eğitmeni', 15);
INSERT INTO professions (id, name, category_id) VALUES (574, 'Antrenör', 15);
INSERT INTO professions (id, name, category_id) VALUES (575, 'Spor yöneticisi', 15);
INSERT INTO professions (id, name, category_id) VALUES (576, 'Kulüp yöneticisi', 15);
INSERT INTO professions (id, name, category_id) VALUES (577, 'Stadyum görevlisi', 15);
INSERT INTO professions (id, name, category_id) VALUES (578, 'Spor salonu görevlisi', 15);
INSERT INTO professions (id, name, category_id) VALUES (579, 'Danışman', 16);
INSERT INTO professions (id, name, category_id) VALUES (580, 'Yönetim danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (581, 'İK danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (582, 'Finans danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (583, 'Hukuk danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (584, 'Eğitim danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (585, 'Kariyer danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (586, 'Psikolojik danışman', 16);
INSERT INTO professions (id, name, category_id) VALUES (587, 'Aile danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (588, 'Evlilik danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (589, 'Çocuk gelişimi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (590, 'Beslenme danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (591, 'Spor beslenme danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (592, 'Moda danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (593, 'İmage danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (594, 'Sosyal medya danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (595, 'Dijital pazarlama danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (596, 'SEO uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (597, 'SEM uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (598, 'İçerik stratejisti', 16);
INSERT INTO professions (id, name, category_id) VALUES (599, 'Marka danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (600, 'Kurumsal iletişim danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (601, 'Kriz yönetimi danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (602, 'İtibar yönetimi danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (603, 'Çevre danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (604, 'Enerji danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (605, 'Gayrimenkul danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (606, 'Emlak danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (607, 'Sigorta danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (608, 'Vergi danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (609, 'Mali müşavir', 16);
INSERT INTO professions (id, name, category_id) VALUES (610, 'Yeminli mali müşavir', 16);
INSERT INTO professions (id, name, category_id) VALUES (611, 'Serbest muhasebeci', 16);
INSERT INTO professions (id, name, category_id) VALUES (612, 'Denetçi', 16);
INSERT INTO professions (id, name, category_id) VALUES (613, 'İç denetçi', 16);
INSERT INTO professions (id, name, category_id) VALUES (614, 'Sertifikalı iç denetçi', 16);
INSERT INTO professions (id, name, category_id) VALUES (615, 'Risk yönetimi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (616, 'Uyum uzmanı ( compliance )', 16);
INSERT INTO professions (id, name, category_id) VALUES (617, 'Kalite yönetimi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (618, 'Süreç iyileştirme uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (619, 'İş analisti', 16);
INSERT INTO professions (id, name, category_id) VALUES (620, 'Proje yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (621, 'Program yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (622, 'Portföy yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (623, 'Ürün yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (624, 'Scrum master', 16);
INSERT INTO professions (id, name, category_id) VALUES (625, 'Agile koçu', 16);
INSERT INTO professions (id, name, category_id) VALUES (626, 'İş geliştirme uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (627, 'Strateji uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (628, 'Operasyon yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (629, 'Tedarik zinciri yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (630, 'Lojistik yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (631, 'Depo yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (632, 'Satın alma uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (633, 'İhale uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (634, 'Sözleşme uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (635, 'Hukuk müşaviri', 16);
INSERT INTO professions (id, name, category_id) VALUES (636, 'İnsan kaynakları uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (637, 'İK yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (638, 'Eğitim ve gelişim uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (639, 'Performans yönetimi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (640, 'Ücret ve yan haklar uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (641, 'İşe alım uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (642, 'Yetenek yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (643, 'Kurumsal kültür uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (644, 'Çeşitlilik ve kapsayıcılık uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (645, 'İş sağlığı ve güvenliği uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (646, 'İş yeri hekimi', 16);
INSERT INTO professions (id, name, category_id) VALUES (647, 'İş güvenliği uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (648, 'Ergonomist', 16);
INSERT INTO professions (id, name, category_id) VALUES (649, 'Çevre mühendisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (650, 'Sürdürülebilirlik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (651, 'Sosyal sorumluluk uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (652, 'Kurumsal sosyal sorumluluk uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (653, 'Gönüllü yönetimi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (654, 'Sivil toplum uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (655, 'Kamu ilişkileri uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (656, 'Lobicist', 16);
INSERT INTO professions (id, name, category_id) VALUES (657, 'Siyasi danışman', 16);
INSERT INTO professions (id, name, category_id) VALUES (658, 'Seçim danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (659, 'Kamuoyu araştırmacısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (660, 'Anketör', 16);
INSERT INTO professions (id, name, category_id) VALUES (661, 'Araştırma uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (662, 'Veri analisti', 16);
INSERT INTO professions (id, name, category_id) VALUES (663, 'İstatistikçi', 16);
INSERT INTO professions (id, name, category_id) VALUES (664, 'Matematikçi', 16);
INSERT INTO professions (id, name, category_id) VALUES (665, 'Fizikçi', 16);
INSERT INTO professions (id, name, category_id) VALUES (666, 'Kimyager', 16);
INSERT INTO professions (id, name, category_id) VALUES (667, 'Biyolog', 16);
INSERT INTO professions (id, name, category_id) VALUES (668, 'Jeolog', 16);
INSERT INTO professions (id, name, category_id) VALUES (669, 'Meteorolog', 16);
INSERT INTO professions (id, name, category_id) VALUES (670, 'Astronom', 16);
INSERT INTO professions (id, name, category_id) VALUES (671, 'Coğrafyacı', 16);
INSERT INTO professions (id, name, category_id) VALUES (672, 'Tarihçi', 16);
INSERT INTO professions (id, name, category_id) VALUES (673, 'Arkeolog', 16);
INSERT INTO professions (id, name, category_id) VALUES (674, 'Antropolog', 16);
INSERT INTO professions (id, name, category_id) VALUES (675, 'Sosyolog', 16);
INSERT INTO professions (id, name, category_id) VALUES (676, 'Psikolog', 16);
INSERT INTO professions (id, name, category_id) VALUES (677, 'Filozof', 16);
INSERT INTO professions (id, name, category_id) VALUES (678, 'Edebiyatçı', 16);
INSERT INTO professions (id, name, category_id) VALUES (679, 'Dilbilimci', 16);
INSERT INTO professions (id, name, category_id) VALUES (680, 'Çevirmen', 16);
INSERT INTO professions (id, name, category_id) VALUES (681, 'Tercüman', 16);
INSERT INTO professions (id, name, category_id) VALUES (682, 'Yeminli tercüman', 16);
INSERT INTO professions (id, name, category_id) VALUES (683, 'Simultane çevirmen', 16);
INSERT INTO professions (id, name, category_id) VALUES (684, 'Konferans çevirmeni', 16);
INSERT INTO professions (id, name, category_id) VALUES (685, 'Yazılı çevirmen', 16);
INSERT INTO professions (id, name, category_id) VALUES (686, 'Yerelleştirme uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (687, 'Teknik çevirmen', 16);
INSERT INTO professions (id, name, category_id) VALUES (688, 'Tıbbi çevirmen', 16);
INSERT INTO professions (id, name, category_id) VALUES (689, 'Hukuki çevirmen', 16);
INSERT INTO professions (id, name, category_id) VALUES (690, 'Finansal çevirmen', 16);
INSERT INTO professions (id, name, category_id) VALUES (691, 'Edebi çevirmen', 16);
INSERT INTO professions (id, name, category_id) VALUES (692, 'Redaktör', 16);
INSERT INTO professions (id, name, category_id) VALUES (693, 'Editör', 16);
INSERT INTO professions (id, name, category_id) VALUES (694, 'Yayıncı', 16);
INSERT INTO professions (id, name, category_id) VALUES (695, 'Kitap editörü', 16);
INSERT INTO professions (id, name, category_id) VALUES (696, 'Dergi editörü', 16);
INSERT INTO professions (id, name, category_id) VALUES (697, 'Gazete editörü', 16);
INSERT INTO professions (id, name, category_id) VALUES (698, 'Web editörü', 16);
INSERT INTO professions (id, name, category_id) VALUES (699, 'İçerik editörü', 16);
INSERT INTO professions (id, name, category_id) VALUES (700, 'Video editörü', 16);
INSERT INTO professions (id, name, category_id) VALUES (701, 'Ses editörü', 16);
INSERT INTO professions (id, name, category_id) VALUES (702, 'Görsel editör', 16);
INSERT INTO professions (id, name, category_id) VALUES (703, 'Fotoğraf editörü', 16);
INSERT INTO professions (id, name, category_id) VALUES (704, 'Grafik editörü', 16);
INSERT INTO professions (id, name, category_id) VALUES (705, 'Sayfa düzenleyici', 16);
INSERT INTO professions (id, name, category_id) VALUES (706, 'Dizgici', 16);
INSERT INTO professions (id, name, category_id) VALUES (707, 'Matbaacı', 16);
INSERT INTO professions (id, name, category_id) VALUES (708, 'Baskı teknisyeni', 16);
INSERT INTO professions (id, name, category_id) VALUES (709, 'Dijital baskı operatörü', 16);
INSERT INTO professions (id, name, category_id) VALUES (710, '3D baskı operatörü', 16);
INSERT INTO professions (id, name, category_id) VALUES (711, 'Lazer kesim operatörü', 16);
INSERT INTO professions (id, name, category_id) VALUES (712, 'CNC operatörü', 16);
INSERT INTO professions (id, name, category_id) VALUES (713, 'CAD/CAM uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (714, 'Teknik ressam', 16);
INSERT INTO professions (id, name, category_id) VALUES (715, 'Maketçi', 16);
INSERT INTO professions (id, name, category_id) VALUES (716, 'Prototip uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (717, 'Ürün tasarımcısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (718, 'Endüstriyel tasarımcı', 16);
INSERT INTO professions (id, name, category_id) VALUES (719, 'Moda tasarımcısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (720, 'Tekstil tasarımcısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (721, 'Mobilya tasarımcısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (722, 'Aydınlatma tasarımcısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (723, 'Ambalaj tasarımcısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (724, 'Grafik tasarımcısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (725, 'Web tasarımcısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (726, 'UI tasarımcısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (727, 'UX tasarımcısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (728, 'Oyun tasarımcısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (729, 'Karakter tasarımcısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (730, 'Çevre tasarımcısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (731, 'Peyzaj tasarımcısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (732, 'Şehir plancısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (733, 'Bölge plancısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (734, 'Ulaşım plancısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (735, 'Altyapı plancısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (736, 'Afet yönetimi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (737, 'Acil durum yönetmeni', 16);
INSERT INTO professions (id, name, category_id) VALUES (738, 'Arama kurtarma uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (739, 'İtfaiyeci', 16);
INSERT INTO professions (id, name, category_id) VALUES (740, 'İstihkâmcı', 16);
INSERT INTO professions (id, name, category_id) VALUES (741, 'Bomba imhacı', 16);
INSERT INTO professions (id, name, category_id) VALUES (742, 'Güvenlik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (743, 'Özel dedektif', 16);
INSERT INTO professions (id, name, category_id) VALUES (744, 'Özel araştırmacı', 16);
INSERT INTO professions (id, name, category_id) VALUES (745, 'Kriminalist', 16);
INSERT INTO professions (id, name, category_id) VALUES (746, 'Kriminoloji uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (747, 'Adli psikolog', 16);
INSERT INTO professions (id, name, category_id) VALUES (748, 'Adli tabip', 16);
INSERT INTO professions (id, name, category_id) VALUES (749, 'Adli tıp uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (750, 'Adli kimya uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (751, 'Adli balistik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (752, 'Adli dijital uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (753, 'Adli bilişim uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (754, 'Siber suç uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (755, 'Terörle mücadele uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (756, 'İstihbarat analisti', 16);
INSERT INTO professions (id, name, category_id) VALUES (757, 'İstihbarat görevlisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (758, 'Güvenlik analisti', 16);
INSERT INTO professions (id, name, category_id) VALUES (759, 'Risk analisti', 16);
INSERT INTO professions (id, name, category_id) VALUES (760, 'Kredi analisti', 16);
INSERT INTO professions (id, name, category_id) VALUES (761, 'Finansal analist', 16);
INSERT INTO professions (id, name, category_id) VALUES (762, 'Yatırım analisti', 16);
INSERT INTO professions (id, name, category_id) VALUES (763, 'Hisse senedi analisti', 16);
INSERT INTO professions (id, name, category_id) VALUES (764, 'Tahvil analisti', 16);
INSERT INTO professions (id, name, category_id) VALUES (765, 'Emtia analisti', 16);
INSERT INTO professions (id, name, category_id) VALUES (766, 'Gayrimenkul analisti', 16);
INSERT INTO professions (id, name, category_id) VALUES (767, 'Pazar analisti', 16);
INSERT INTO professions (id, name, category_id) VALUES (768, 'Sektör analisti', 16);
INSERT INTO professions (id, name, category_id) VALUES (769, 'Rekabet analisti', 16);
INSERT INTO professions (id, name, category_id) VALUES (770, 'Müşteri analisti', 16);
INSERT INTO professions (id, name, category_id) VALUES (771, 'Davranış analisti', 16);
INSERT INTO professions (id, name, category_id) VALUES (772, 'İş zekası uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (773, 'Veri ambarı uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (774, 'ETL uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (775, 'Veri modelleme uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (776, 'Veri yönetimi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (777, 'Veri kalitesi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (778, 'Veri gizliliği uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (779, 'Veri güvenliği uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (780, 'Bilgi güvenliği uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (781, 'Ağ güvenliği uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (782, 'Uygulama güvenliği uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (783, 'Bulut güvenliği uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (784, 'Mobil güvenlik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (785, 'IoT güvenliği uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (786, 'Blockchain güvenliği uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (787, 'Kripto para uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (788, 'Blockchain geliştiricisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (789, 'Akıllı sözleşme geliştiricisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (790, 'DeFi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (791, 'NFT uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (792, 'Metaverse uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (793, 'Sanal gerçeklik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (794, 'Artırılmış gerçeklik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (795, 'Karma gerçeklik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (796, 'Oyun geliştiricisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (797, 'Oyun sanatçısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (798, 'Oyun animatörü', 16);
INSERT INTO professions (id, name, category_id) VALUES (799, 'Oyun test uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (800, 'Oyun yayıncısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (801, 'E-spor oyuncusu', 16);
INSERT INTO professions (id, name, category_id) VALUES (802, 'E-spor koçu', 16);
INSERT INTO professions (id, name, category_id) VALUES (803, 'E-spor menajeri', 16);
INSERT INTO professions (id, name, category_id) VALUES (804, 'E-spor yorumcusu', 16);
INSERT INTO professions (id, name, category_id) VALUES (805, 'Canlı yayıncı', 16);
INSERT INTO professions (id, name, category_id) VALUES (806, 'İçerik üretici', 16);
INSERT INTO professions (id, name, category_id) VALUES (807, 'Sosyal medya yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (808, 'Sosyal medya uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (809, 'Topluluk yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (810, 'Dijital pazarlama uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (811, 'E-posta pazarlama uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (812, 'İçerik pazarlama uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (813, 'Video pazarlama uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (814, 'Influencer pazarlama uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (815, 'Affiliate pazarlama uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (816, 'Growth hacker', 16);
INSERT INTO professions (id, name, category_id) VALUES (817, 'Dönüşüm optimizasyonu uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (818, 'Kullanıcı edinme uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (819, 'Müşteri deneyimi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (820, 'Müşteri başarı uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (821, 'Müşteri destek uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (822, 'Teknik destek uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (823, 'Yardım masası uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (824, 'Uzaktan destek uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (825, 'Alan destek uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (826, 'Saha destek uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (827, 'Sistem destek uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (828, 'Ağ destek uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (829, 'Uygulama destek uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (830, 'Veritabanı destek uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (831, 'Bulut destek uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (832, 'ERP destek uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (833, 'CRM destek uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (834, 'SAP uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (835, 'Oracle uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (836, 'Microsoft uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (837, 'Linux uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (838, 'Windows uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (839, 'Mac uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (840, 'iOS uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (841, 'Android uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (842, 'Web geliştirici', 16);
INSERT INTO professions (id, name, category_id) VALUES (843, 'Frontend geliştirici', 16);
INSERT INTO professions (id, name, category_id) VALUES (844, 'Backend geliştirici', 16);
INSERT INTO professions (id, name, category_id) VALUES (845, 'Full stack geliştirici', 16);
INSERT INTO professions (id, name, category_id) VALUES (846, 'Mobil geliştirici', 16);
INSERT INTO professions (id, name, category_id) VALUES (847, 'Oyun geliştirici', 16);
INSERT INTO professions (id, name, category_id) VALUES (848, 'Gömülü sistem geliştiricisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (849, 'Firmware geliştiricisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (850, 'Donanım geliştiricisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (851, 'FPGA geliştiricisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (852, 'ASIC geliştiricisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (853, 'Devre tasarımcısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (854, 'PCB tasarımcısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (855, 'RF mühendisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (856, 'Telekomünikasyon mühendisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (857, 'Optik mühendisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (858, 'Biyomedikal mühendisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (859, 'Tıbbi cihaz mühendisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (860, 'Protez uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (861, 'Ortez uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (862, 'Tıbbi görüntüleme uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (863, 'Radyasyon güvenliği uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (864, 'Nükleer tıp uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (865, 'Radyofarmasötik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (866, 'Tıbbi fizik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (867, 'Biyofizikçi', 16);
INSERT INTO professions (id, name, category_id) VALUES (868, 'Biyokimyager', 16);
INSERT INTO professions (id, name, category_id) VALUES (869, 'Biyoteknoloji uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (870, 'Genetik mühendisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (871, 'Biyoinformatikçi', 16);
INSERT INTO professions (id, name, category_id) VALUES (872, 'Farmakolog', 16);
INSERT INTO professions (id, name, category_id) VALUES (873, 'Toksikolog', 16);
INSERT INTO professions (id, name, category_id) VALUES (874, 'Eczacı', 16);
INSERT INTO professions (id, name, category_id) VALUES (875, 'Eczane teknisyeni', 16);
INSERT INTO professions (id, name, category_id) VALUES (876, 'Eczane kalfası', 16);
INSERT INTO professions (id, name, category_id) VALUES (877, 'İlaç temsilcisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (878, 'Tıbbi mümessil', 16);
INSERT INTO professions (id, name, category_id) VALUES (879, 'Medikal satış temsilcisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (880, 'Tıbbi cihaz satış temsilcisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (881, 'Laboratuvar cihazları uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (882, 'Laboratuvar yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (883, 'Klinik araştırma uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (884, 'Klinik deney koordinatörü', 16);
INSERT INTO professions (id, name, category_id) VALUES (885, 'Biyoistatistikçi', 16);
INSERT INTO professions (id, name, category_id) VALUES (886, 'Epidemiyolog', 16);
INSERT INTO professions (id, name, category_id) VALUES (887, 'Halk sağlığı uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (888, 'Çevre sağlığı uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (889, 'Gıda güvenliği uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (890, 'Su kalitesi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (891, 'Hava kalitesi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (892, 'Toprak bilimci', 16);
INSERT INTO professions (id, name, category_id) VALUES (893, 'Jeomorfolog', 16);
INSERT INTO professions (id, name, category_id) VALUES (894, 'Hidrolog', 16);
INSERT INTO professions (id, name, category_id) VALUES (895, 'Oşinograf', 16);
INSERT INTO professions (id, name, category_id) VALUES (896, 'Paleontolog', 16);
INSERT INTO professions (id, name, category_id) VALUES (897, 'Mineralog', 16);
INSERT INTO professions (id, name, category_id) VALUES (898, 'Petrograf', 16);
INSERT INTO professions (id, name, category_id) VALUES (899, 'Petrolog', 16);
INSERT INTO professions (id, name, category_id) VALUES (900, 'Jeokimyager', 16);
INSERT INTO professions (id, name, category_id) VALUES (901, 'Jeofizikçi', 16);
INSERT INTO professions (id, name, category_id) VALUES (902, 'Sismolog', 16);
INSERT INTO professions (id, name, category_id) VALUES (903, 'Volkanolog', 16);
INSERT INTO professions (id, name, category_id) VALUES (904, 'Klimatolog', 16);
INSERT INTO professions (id, name, category_id) VALUES (905, 'Hava tahmin uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (906, 'Uydu görüntüleme uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (907, 'Uzay bilimci', 16);
INSERT INTO professions (id, name, category_id) VALUES (908, 'Uzay mühendisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (909, 'Roket mühendisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (910, 'Uçak mühendisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (911, 'Helikopter mühendisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (912, 'İHA mühendisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (913, 'SİHA mühendisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (914, 'Uzay aracı mühendisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (915, 'Uydu mühendisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (916, 'Uydu operatörü', 16);
INSERT INTO professions (id, name, category_id) VALUES (917, 'Uzay istasyonu uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (918, 'Astronot', 16);
INSERT INTO professions (id, name, category_id) VALUES (919, 'Kozmonot', 16);
INSERT INTO professions (id, name, category_id) VALUES (920, 'Taikonaut', 16);
INSERT INTO professions (id, name, category_id) VALUES (921, 'Uzay turizmi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (922, 'Uzay hukuku uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (923, 'Uzay politikası uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (924, 'Uzay güvenliği uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (925, 'Uzay çöpü uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (926, 'Uzay madenciliği uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (927, 'Uzay kaynakları uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (928, 'Uzay tarımı uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (929, 'Uzay biyolojisi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (930, 'Uzay tıbbı uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (931, 'Uzay psikolojisi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (932, 'Uzay eğitimi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (933, 'Uzay turizmi rehberi', 16);
INSERT INTO professions (id, name, category_id) VALUES (934, 'Uzay fotoğrafçısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (935, 'Uzay sanatçısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (936, 'Uzay yazarlığı uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (937, 'Uzay gazeteciliği uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (938, 'Uzay iletişim uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (939, 'Uzay diplomasisi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (940, 'Uzay savunma uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (941, 'Uzay istihbarat uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (942, 'Uzay gözlem uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (943, 'Uzay keşif uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (944, 'Uzay kolonizasyonu uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (945, 'Uzay yerleşim uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (946, 'Uzay mimarı', 16);
INSERT INTO professions (id, name, category_id) VALUES (947, 'Uzay inşaat mühendisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (948, 'Uzay tesisatçısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (949, 'Uzay elektrikçisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (950, 'Uzay doktoru', 16);
INSERT INTO professions (id, name, category_id) VALUES (951, 'Uzay cerrahı', 16);
INSERT INTO professions (id, name, category_id) VALUES (952, 'Uzay diş hekimi', 16);
INSERT INTO professions (id, name, category_id) VALUES (953, 'Uzay psikologu', 16);
INSERT INTO professions (id, name, category_id) VALUES (954, 'Uzay beslenme uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (955, 'Uzay egzersiz uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (956, 'Uzay fizyoterapisti', 16);
INSERT INTO professions (id, name, category_id) VALUES (957, 'Uzay hemşiresi', 16);
INSERT INTO professions (id, name, category_id) VALUES (958, 'Uzay eczacısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (959, 'Uzay laboratuvar teknisyeni', 16);
INSERT INTO professions (id, name, category_id) VALUES (960, 'Uzay araştırmacısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (961, 'Uzay bilim insanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (962, 'Uzay teknisyeni', 16);
INSERT INTO professions (id, name, category_id) VALUES (963, 'Uzay operatörü', 16);
INSERT INTO professions (id, name, category_id) VALUES (964, 'Uzay kontrolörü', 16);
INSERT INTO professions (id, name, category_id) VALUES (965, 'Uzay navigasyon uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (966, 'Uzay haberleşme uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (967, 'Uzay radar uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (968, 'Uzay optik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (969, 'Uzay lazer uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (970, 'Uzay enerjisi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (971, 'Uzay güneş enerjisi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (972, 'Uzay nükleer enerjisi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (973, 'Uzay batarya uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (974, 'Uzay yakıt uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (975, 'Uzay itki uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (976, 'Uzay roket motoru uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (977, 'Uzay hipersonik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (978, 'Uzay hipersonik araç mühendisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (979, 'Uzay hipersonik aerodinamik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (980, 'Uzay termal uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (981, 'Uzay ısı kalkanı uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (982, 'Uzay malzeme uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (983, 'Uzay kompozit uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (984, 'Uzay seramik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (985, 'Uzay metal uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (986, 'Uzay alaşım uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (987, 'Uzay nanoteknoloji uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (988, 'Uzay biyomimetik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (989, 'Uzay robotik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (990, 'Uzay yapay zeka uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (991, 'Uzay otonom sistem uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (992, 'Uzay insansız sistem uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (993, 'Uzay dron uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (994, 'Uzay robot uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (995, 'Uzay exoskeleton uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (996, 'Uzay protez uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (997, 'Uzay 3D baskı uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (998, 'Uzay üretim uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (999, 'Uzay fabrikasyon uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1000, 'Uzay montaj uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1001, 'Uzay bakım uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1002, 'Uzay onarım uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1003, 'Uzay geri dönüşüm uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1004, 'Uzay yaşam destek uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1005, 'Uzay atmosfer uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1006, 'Uzay basınç uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1007, 'Uzay sıcaklık uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1008, 'Uzay nem uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1009, 'Uzay hava kalitesi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1010, 'Uzay su geri dönüşüm uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1011, 'Uzay atık yönetimi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1012, 'Uzay gıda üretimi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1013, 'Uzay hidroponik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1014, 'Uzay aeroponik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1015, 'Uzay topraksız tarım uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1016, 'Uzay bitki yetiştiricisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (1017, 'Uzay hayvan yetiştiricisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (1018, 'Uzay balık yetiştiricisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (1019, 'Uzay mikrobiyal sistem uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1020, 'Uzay biyoreaktör uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1021, 'Uzay sentetik biyoloji uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1022, 'Uzay genetik mühendisliği uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1023, 'Uzay klonlama uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1024, 'Uzay doku mühendisliği uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1025, 'Uzay organ yetiştirme uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1026, 'Uzay kan üretimi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1027, 'Uzay ilaç üretimi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1028, 'Uzay vaksin üretimi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1029, 'Uzay antibiyotik üretimi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1030, 'Uzay enzim üretimi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1031, 'Uzay hormon üretimi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1032, 'Uzay protein üretimi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1033, 'Uzay besin takviyesi üretimi uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1034, 'Uzay fonksiyonel gıda uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1035, 'Uzay uzun ömürlü gıda uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1036, 'Uzay dondurulmuş gıda uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1037, 'Uzay liyofilize gıda uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1038, 'Uzay radyasyon işlenmiş gıda uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1039, 'Uzay uzay mutfağı şefi', 16);
INSERT INTO professions (id, name, category_id) VALUES (1040, 'Uzay uzay gıda teknisyeni', 16);
INSERT INTO professions (id, name, category_id) VALUES (1041, 'Uzay uzay beslenme danışmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1042, 'Uzay uzay diyetisyeni', 16);
INSERT INTO professions (id, name, category_id) VALUES (1043, 'Uzay uzay spor hekimi', 16);
INSERT INTO professions (id, name, category_id) VALUES (1044, 'Uzay uzay spor psikologu', 16);
INSERT INTO professions (id, name, category_id) VALUES (1045, 'Uzay uzay spor antrenörü', 16);
INSERT INTO professions (id, name, category_id) VALUES (1046, 'Uzay uzay spor fizyoterapisti', 16);
INSERT INTO professions (id, name, category_id) VALUES (1047, 'Uzay uzay spor masörü', 16);
INSERT INTO professions (id, name, category_id) VALUES (1048, 'Uzay uzay spor masözü', 16);
INSERT INTO professions (id, name, category_id) VALUES (1049, 'Uzay uzay spor beslenme uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1050, 'Uzay uzay spor ekipmanı uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1051, 'Uzay uzay spor kıyafeti uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1052, 'Uzay uzay spor ayakkabısı uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1053, 'Uzay uzay spor güvenliği uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1054, 'Uzay uzay spor yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (1055, 'Uzay uzay spor menajeri', 16);
INSERT INTO professions (id, name, category_id) VALUES (1056, 'Uzay uzay spor hukuku uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1057, 'Uzay uzay spor iletişim uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1058, 'Uzay uzay spor pazarlama uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1059, 'Uzay uzay spor sponsorluk uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1060, 'Uzay uzay spor etkinlik yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (1061, 'Uzay uzay spor stadyum yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (1062, 'Uzay uzay spor tesis yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (1063, 'Uzay uzay spor kulüp yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (1064, 'Uzay uzay spor federasyonu uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1065, 'Uzay uzay spor olimpiyat uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1066, 'Uzay uzay spor paralimpik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1067, 'Uzay uzay spor özel olimpiyat uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1068, 'Uzay uzay spor e-spor uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1069, 'Uzay uzay spor sanal spor uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1070, 'Uzay uzay spor uzay spor uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1071, 'Uzay uzay spor yerçekimsiz spor uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1072, 'Uzay uzay spor yerçekimli spor uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1073, 'Uzay uzay spor uzay yürüyüşü uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1074, 'Uzay uzay spor uzay koşusu uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1075, 'Uzay uzay spor uzay yüzme uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1076, 'Uzay uzay spor uzay jimnastik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1077, 'Uzay uzay spor uzay güreş uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1078, 'Uzay uzay spor uzay boks uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1079, 'Uzay uzay spor uzay judo uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1080, 'Uzay uzay spor uzay karate uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1081, 'Uzay uzay spor uzay taekwondo uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1082, 'Uzay uzay spor uzay cimnastik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1083, 'Uzay uzay spor uzay atletizm uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1084, 'Uzay uzay spor uzay atıcılık uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1085, 'Uzay uzay spor uzay okçuluk uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1086, 'Uzay uzay spor uzay binicilik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1087, 'Uzay uzay spor uzay binicilik at yetiştiricisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (1088, 'Uzay uzay spor uzay binicilik at bakıcısı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1089, 'Uzay uzay spor uzay binicilik at terbiyecisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (1090, 'Uzay uzay spor uzay binicilik at eğitmeni', 16);
INSERT INTO professions (id, name, category_id) VALUES (1091, 'Uzay uzay spor uzay binicilik at veterineri', 16);
INSERT INTO professions (id, name, category_id) VALUES (1092, 'Uzay uzay spor uzay binicilik at diş hekimi', 16);
INSERT INTO professions (id, name, category_id) VALUES (1093, 'Uzay uzay spor uzay binicilik at masörü', 16);
INSERT INTO professions (id, name, category_id) VALUES (1094, 'Uzay uzay spor uzay binicilik at beslenme uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1095, 'Uzay uzay spor uzay binicilik at ekipmanı uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1096, 'Uzay uzay spor uzay binicilik at güvenliği uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1097, 'Uzay uzay spor uzay binicilik at yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (1098, 'Uzay uzay spor uzay binicilik at menajeri', 16);
INSERT INTO professions (id, name, category_id) VALUES (1099, 'Uzay uzay spor uzay binicilik at hukuku uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1100, 'Uzay uzay spor uzay binicilik at iletişim uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1101, 'Uzay uzay spor uzay binicilik at pazarlama uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1102, 'Uzay uzay spor uzay binicilik at sponsorluk uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1103, 'Uzay uzay spor uzay binicilik at etkinlik yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (1104, 'Uzay uzay spor uzay binicilik at stadyum yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (1105, 'Uzay uzay spor uzay binicilik at tesis yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (1106, 'Uzay uzay spor uzay binicilik at kulüp yöneticisi', 16);
INSERT INTO professions (id, name, category_id) VALUES (1107, 'Uzay uzay spor uzay binicilik at federasyonu uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1108, 'Uzay uzay spor uzay binicilik at olimpiyat uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1109, 'Uzay uzay spor uzay binicilik at paralimpik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1110, 'Uzay uzay spor uzay binicilik at özel olimpiyat uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1111, 'Uzay uzay spor uzay binicilik at e-spor uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1112, 'Uzay uzay spor uzay binicilik at sanal spor uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1113, 'Uzay uzay spor uzay binicilik at uzay spor uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1114, 'Uzay uzay spor uzay binicilik at yerçekimsiz spor uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1115, 'Uzay uzay spor uzay binicilik at yerçekimli spor uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1116, 'Uzay uzay spor uzay binicilik at uzay yürüyüşü uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1117, 'Uzay uzay spor uzay binicilik at uzay koşusu uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1118, 'Uzay uzay spor uz ay binicilik at uzay yüzme uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1119, 'Uzay uzay spor uzay binicilik at uzay jimnastik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1120, 'Uzay uzay spor uzay binicilik at uzay güreş uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1121, 'Uzay uzay spor uzay binicilik at uzay boks uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1122, 'Uzay uzay spor uzay binicilik at uzay judo uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1123, 'Uzay uzay spor uzay binicilik at uzay karate uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1124, 'Uzay uzay spor uzay binicilik at uzay taekwondo uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1125, 'Uzay uzay spor uzay binicilik at uzay cimnastik uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1126, 'Uzay uzay spor uzay binicilik at uzay atletizm uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1127, 'Uzay uzay spor uzay binicilik at uzay atıcılık uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1128, 'Uzay uzay spor uzay binicilik at uzay okçuluk uzmanı', 16);
INSERT INTO professions (id, name, category_id) VALUES (1129, 'Uzay uzay spor uzay binicilik at uzay binicilik uzmanı', 16);

-- Ornek sorgular
-- SELECT * FROM categories ORDER BY sort_order;
-- SELECT p.name FROM professions p JOIN categories c ON p.category_id = c.id WHERE c.id = 1;
-- SELECT * FROM professions WHERE name ILIKE '%muhendis%';
-- SELECT c.name, COUNT(*) FROM professions p JOIN categories c ON p.category_id = c.id GROUP BY c.name;
